add psi and cpv documentation
greco-project/pvcompare pull request #119
Opened 2020-10-21 10:17 UTC by Piranias

Fix #Issue

**Changes proposed in this pull request**:
- add documentation for CPV and PEROSI technologies

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2020-10-21 14:19 UTC, Piranias commented
one function does not come our right. There is a bug 

`This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
`
locally it is displayed correctly, even though it already shows these errors also locally.. any idea?

2020-10-27 14:23 UTC, Piranias commented
@SabineHaas There is still one function that does not dislay correctly. 
see https://pvcompare.readthedocs.io/en/documentation/pv_feedin.html

I have no idea how to change this. I already added some extensions to the config.py but it didnt help. Do you have any idea?

2020-10-29 15:37 UTC, SabineHaas requested changes
Nice work, and a lot of information :) 

General comments:
- We should decide on "pvcompare" or "PVcompare". I would say "pvcompare" and write it kursive in the docs.
- Did you ask for permission of using the figures?  If not, I can ask.
- Could you add references like in MVS please? With a reference section at the end of the page.
- figure captions are not displayed

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The silicone module parameters are loaded from cec module database. The module
could you add a link please?

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +But any other module can be selected.
Do you have to hard-code it or how can you select it? If hard-coded, please write an issue, to change this later.

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The timeseries is calculating making usage of the `Modelchain  <https://pvlib-python.readthedocs.io/en/stable/modelchain.html>`_
```suggestion
The time series is calculated by making usage of the `Modelchain  <https://pvlib-python.readthedocs.io/en/stable/modelchain.html>`_
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +conditions the following methods are added to the `modelchain object <https://pvlib-python.readthedocs.io/en/stable/api.html#modelchain>`_ :
are "selected"? I think the methods already exist and you select them by setting parameters in the modelchain.

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The CPV technology that is used in the pvcopare simulations is a hybrid
```suggestion
The CPV technology that is used in the pvcompare simulations is a hybrid
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +contains the wrapper function `apply_cpvlib_StaticHybridSystem`.
please add a link to the function

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +Previously implemented for CPV in PVSYST. The approach uses the single diode
```suggestion
previously implemented for CPV in PVSYST. The approach uses the single diode
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +Input parameters are weather data with AM (airmass), Temoerature,
```suggestion
Input parameters are weather data with AM (airmass), temperature,
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +flatplate submodule
```suggestion
Flatplate submodule
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +is considered. For Aoi > 60 ° GII is considered because DII and DHI come through.
Maybe this way it's easier to understand:
For AOI < 60° only the diffuse irradiance reaches the flate plate module, which is why ... : GII (global inclined irradiance) - DII (direct inclined irradiance). 
For Aoi > 60 ° also DII and DHI fall onto the flate plate module, which is why...

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +input irradiance. No module connection is assumed, so cpv and flatplate output
```suggestion
input irradiance. No module connection is assumed, so CPV and flat plate output
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The perovskite silicone cell is a high efficiency cell that is still in it's
```suggestion
The perovskite-silicon cell is a high-efficiency cell that is still in its
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +tandem e.g perovskite - silicone cells, which we will focus on here.
of perovskite in tandem cells?

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +are of great impact for multijunction cells.
```suggestion
are of great impact for multi-junction cells.
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +input data
```suggestion
Input data
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The cell parameters provided in pvcompare are for the cells (Korte...) ith 17 %
reference is missing

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +modeling procedure
```suggestion
Modeling procedure
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +The POA_global (plane of array) irradiance is calculated with `pvlib.irradiance.get_total_irradiance() <https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.irradiance.get_total_irradiance.h
```suggestion
The POA_global (plane of array) irradiance is calculated with the `pvlib.irradiance.get_total_irradiance() <https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.irradiance.get_total_irradiance.html#pvlib.irradiance.get_total_irradiance>`_ function
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +3.2 losses due to cell connection (5%) and cell to module connection (5%) are
```suggestion
3.2 Losses due to cell connection (5%) and cell to module connection (5%) are
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +taken into account
```suggestion
taken into account.
```

2020-10-29 15:37 UTC, SabineHaas commented on docs/pv_feedin.rst
> +* This procedure calculates the maximum powerpoint for realorld conditions at irr_ref = 1000 W/qm and temp_ref = 25 °.
```suggestion
* This procedure calculates the maximum power point for real world conditions at irr_ref = 1000 W/qm and temp_ref = 25°C.
```

2020-10-29 15:37 UTC, SabineHaas commented on pvcompare/cpv/apply_cpvlib_StaticHybridSystem.py
> +    provided. If you want to add you own module data please do this in
Something is missing in the end

2020-10-29 15:37 UTC, SabineHaas commented on pvcompare/perosi/pvlib_smarts.py
> +        all output variables can be found in the SMARTS 2.9.5 documentation
can you provide a link?

2020-10-29 15:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        False).
I think the parameter is called `normalization` now.

2020-10-29 16:55 UTC, SabineHaas commented on docs/pv_feedin.rst
> +        1 + (x - x_{thrd}) \cdot S_{x\leq x_{thrd}}&         & \text{if }    x &\geq x_{thrd}
Above and below the same before if ? (sorry if I'm to tired to find the difference :D)

2020-11-02 08:04 UTC, Piranias commented on pvcompare/pv_feedin.py
> +        False).
true!

2020-11-02 08:12 UTC, Piranias commented on pvcompare/pv_feedin.py
> +        False).
this has been changed in dev already

2020-11-02 08:38 UTC, Piranias commented on pvcompare/perosi/pvlib_smarts.py
> +        all output variables can be found in the SMARTS 2.9.5 documentation
>     * Could you add references like in MVS please? With a reference section at the end of the page.

What do you mean exactly? I didn't see any reference section at the end of the page in mvs. can you give me an example link?

2020-11-02 08:39 UTC, Piranias commented
* Could you add references like in MVS please? With a reference section at the end of the page.

What do you mean exactly? I didn't see any reference section at the end of the page in mvs. can you give me an example link?

2020-11-02 09:28 UTC, Piranias commented on pvcompare/perosi/pvlib_smarts.py
> +        all output variables can be found in the SMARTS 2.9.5 documentation
done

2020-11-02 09:28 UTC, Piranias commented on pvcompare/cpv/apply_cpvlib_StaticHybridSystem.py
> +    provided. If you want to add you own module data please do this in
done

2020-11-02 09:28 UTC, Piranias commented on docs/pv_feedin.rst
> +        1 + (x - x_{thrd}) \cdot S_{x\leq x_{thrd}}&         & \text{if }    x &\geq x_{thrd}
done

2020-11-02 12:06 UTC, SabineHaas approved these changes
Approved after the following changes:
- display caption of second figure https://pvcompare.readthedocs.io/en/documentation/pv_feedin.html

2020-11-02 13:10 UTC, merged