Fix/hp chiller temps
greco-project/pvcompare pull request #133
Opened 2020-11-04 18:11 UTC by MaGering

Fix #Issue https://github.com/greco-project/pvcompare/issues/59

With this PR the wrong definition of the temperatures are fixed in the code.
start_temperature is obsolete under the current state of heat_pump_and_chiller.py. 
room_temperature cannot be determined as described in the issue. For this reason temp_high and temp_low were passed for both technologies.

Furthermore for both technologies the quality grades had been chosen from UPM's validation data (https://oemof-thermal.readthedocs.io/en/latest/validation_compression_heat_pumps_and_chillers.html)
For the heat pump temp_high has been chosen from the highest value of the evaporators temperature during UPM's measurement. For temp_low the heating limit temperature (Heizgrenztemperatur) has been chosen.

The temperature of the chiller could not be obtained from the measurements since other temperature ranges had been driven there. The low temperature has been set for now to 15° C, a temperature lower the comfort temperature of 20–22 °C.
temp_high has been set to 20° C (leaving a range of 5 °C between both temperatures for operation). The chiller has not been implemented in the model yet. However, should it been done so in the future, these temperatures must be researched and adjusted.

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2020-11-05 08:32 UTC, SabineHaas reviewed
Thank you @MaGering ! :+1: 

I only have two comments:
- Although the parameter documentation will be revised, could you please add the changes to the point 'heat_pumps_and_chillers:' in this [section](https://pvcompare.readthedocs.io/en/latest/parameters.html#pvcompare-specific-parameters 
)?
- Does the user have to provide a value for `temp_high` for chillers and for `temp_low` for heat pumps?

2020-11-05 08:33 UTC, SabineHaas commented
> Furthermore for both technologies the quality grades had been chosen from UPM's validation data (https://oemof-thermal.readthedocs.io/en/latest/validation_compression_heat_pumps_and_chillers.html)
> For the heat pump temp_high has been chosen from the highest value of the evaporators temperature during UPM's measurement. For temp_low the heating limit temperature (Heizgrenztemperatur) has been chosen.
> 
> The temperature of the chiller could not be obtained from the measurements since other temperature ranges had been driven there. The low temperature has been set for now to 15° C, a temperature lower the comfort temperature of 20–22 °C.
> temp_high has been set to 20° C (leaving a range of 5 °C between both temperatures for operation). The chiller has not been implemented in the model yet. However, should it been done so in the future, these temperatures must be researched and adjusted.

You could use these explanations for the documentation.

2020-11-05 11:11 UTC, MaGering commented
> > Furthermore for both technologies the quality grades had been chosen from UPM's validation data (https://oemof-thermal.readthedocs.io/en/latest/validation_compression_heat_pumps_and_chillers.html)
> > For the heat pump temp_high has been chosen from the highest value of the evaporators temperature during UPM's measurement. For temp_low the heating limit temperature (Heizgrenztemperatur) has been chosen.
> > The temperature of the chiller could not be obtained from the measurements since other temperature ranges had been driven there. The low temperature has been set for now to 15° C, a temperature lower the comfort temperature of 20–22 °C.
> > temp_high has been set to 20° C (leaving a range of 5 °C between both temperatures for operation). The chiller has not been implemented in the model yet. However, should it been done so in the future, these temperatures must be researched and adjusted.
> 
> You could use these explanations for the documentation.

Good idea! Should I put it at the end of the section 'heat_pumps_and_chillers:' or is the another place you have thought of?

2020-11-05 11:16 UTC, SabineHaas commented
> Good idea! Should I put it at the end of the section 'heat_pumps_and_chillers:' or is the another place you have thought of?

Yes, sounds good 👍

2020-11-05 11:16 UTC, MaGering commented
>     * Does the user have to provide a value for `temp_high` for chillers and for `temp_low` for heat pumps?

Right now they don't. Should we put it to None?

2020-11-05 11:38 UTC, MaGering commented
There is another question I have:

Should we already implement input values of the different technologies in this PR? The temperatures I adapted so far only belong to air/air technologies. If yes, I would rename the mode in the input file technology-specific. E.g.: heat_pump_air_air, heat_pump_brine_water

What do you think?

2020-11-05 12:50 UTC, SabineHaas commented
> There is another question I have:
> 
> Should we already implement input values of the different technologies in this PR? The temperatures I adapted so far only belong to air/air technologies. If yes, I would rename the mode in the input file technology-specific. E.g.: heat_pump_air_air, heat_pump_brine_water
> 
> What do you think?

I would rather keep only one input file, that is not technology specific and provide the technology-specific parameters in another format. Maybe in the ([PARAMETERS_mvs_inputs](https://github.com/greco-project/pvcompare/tree/dev/pvcompare/data/PARAMETERS_mvs_inputs)). Then we could rename it to `PARAMETERS_inputs`.

2020-11-05 15:06 UTC, MaGering commented
> > There is another question I have:
> > Should we already implement input values of the different technologies in this PR? The temperatures I adapted so far only belong to air/air technologies. If yes, I would rename the mode in the input file technology-specific. E.g.: heat_pump_air_air, heat_pump_brine_water
> > What do you think?
> 
> I would rather keep only one input file, that is not technology specific and provide the technology-specific parameters in another format. Maybe in the ([PARAMETERS_mvs_inputs](https://github.com/greco-project/pvcompare/tree/dev/pvcompare/data/PARAMETERS_mvs_inputs)). Then we could rename it to `PARAMETERS_inputs`.

I see! All the values in the pvcompare input are technology dependent right now. For air/air technology we chose 35 °C as the high temperature but for brine/water it would be higher. Should we leave air/air as the only technology in the input data right now and find a general approach for the future later on?

2020-11-05 16:14 UTC, SabineHaas commented
> > > There is another question I have:
> > > Should we already implement input values of the different technologies in this PR? The temperatures I adapted so far only belong to air/air technologies. If yes, I would rename the mode in the input file technology-specific. E.g.: heat_pump_air_air, heat_pump_brine_water
> > > What do you think?
> > 
> > 
> > I would rather keep only one input file, that is not technology specific and provide the technology-specific parameters in another format. Maybe in the ([PARAMETERS_mvs_inputs](https://github.com/greco-project/pvcompare/tree/dev/pvcompare/data/PARAMETERS_mvs_inputs)). Then we could rename it to `PARAMETERS_inputs`.
> 
> I see! All the values in the pvcompare input are technology dependent right now. For air/air technology we chose 35 °C as the high temperature but for brine/water it would be higher. Should we leave air/air as the only technology in the input data right now and find a general approach for the future later on?

That sounds like a good idea!

2020-11-09 07:33 UTC, SabineHaas requested changes

2020-11-09 07:33 UTC, SabineHaas commented on tests/test_data/test_inputs_heat/heat_pumps_and_chillers.csv
> +chiller,0.3,nan,15,,
I'd suggest to leave spaces in the csvs empty instead of writing "nan"... or translated to the view above it would be e.g. `"chiller,0.3,,15,,"`.
The empty spaces will be read as `nans` by `pandas.read_csv()`.

2020-11-13 19:41 UTC, MaGering commented on tests/test_data/test_inputs_heat/heat_pumps_and_chillers.csv
> +chiller,0.3,nan,15,,
Very nice. :)
Done with commit https://github.com/greco-project/pvcompare/pull/133/commits/8dfdc90171bdee82b58e245f04d7ea1abd70f78d

2020-11-13 20:10 UTC, MaGering commented
Even though I applied black on test_heat_pump_and_chiller.py the checks are failing. The message says 
`would reformat /home/travis/build/greco-project/pvcompare/tests/test_heat_pump_and_chiller.py`

 I don't get this since black tells me 
```
All done! ✨ 🍰 ✨
1 file left unchanged.
```
when I'm trying to run it for `test_heat_pump_and_chiller.py` again.

Do you know how to fix this @SabineHaas ?

2020-11-16 08:40 UTC, SabineHaas commented
Could you check your version of black? It should be `19.10b0` as defined in the [setup.py](https://github.com/greco-project/pvcompare/blob/447a040b42787176ac110a1fce2e5fa43a669690/setup.py#L50), because this is the version travis-ci uses. If you already have the right version please ask @Piranias how she has solved the problem for herself.

2020-11-16 08:56 UTC, SabineHaas approved these changes
Approved after my comments and after checks have passed.

2020-11-16 08:56 UTC, SabineHaas commented on docs/parameters.rst
> +<<<<<<< HEAD
Here's something left from a merge conflict - could you check this please?

2020-11-16 08:56 UTC, SabineHaas commented on docs/parameters.rst
> +    4. **temp_low**: float, temperature of the source (external outlet temperature at the evaporator), default: heating 15 °C ('Reference <http://wiki.energie-m.de/Heizgrenztemperatur>`_)  or 17 °C (
I think this reference belongs to the heating limit temperature.

2020-11-16 09:51 UTC, MaGering commented
> Could you check your version of black? It should be `19.10b0` as defined in the [setup.py](https://github.com/greco-project/pvcompare/blob/447a040b42787176ac110a1fce2e5fa43a669690/setup.py#L50), because this is the version travis-ci uses. If you already have the right version please ask @Piranias how she has solved the problem for herself.

Thank you for this hint! The checks passed with the correct version.

2020-11-17 13:40 UTC, c-moeller approved these changes

2020-11-17 14:04 UTC, merged