Remove summer heat demand and distributes excess demand over the profile
greco-project/pvcompare pull request #137
Opened 2020-11-06 19:02 UTC by MaGering

Fix #Issue https://github.com/greco-project/pvcompare/issues/136

With this PR heat demand during summer is removed from an implemented daily mean temperature (right now 15 °C) on. This excess heat demand is then distributed equally over the remaining heat demand.

The function is used as an enhancement of the [demandlib](https://github.com/oemof/demandlib), which calculates heat demands only above zero. For modelling the heat demand without warm water of dwelling and houses an approach is needed to approximate to the real heating behavior.

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2020-11-09 08:17 UTC, SabineHaas requested changes
Thank you @MaGering for solving this issue! 

- Could you add a docstring to your new function? There's a good example e.g. in `shift_working_hours()`.
- Please add tests for `adjust_heat_demand()`. If you need examples you can look into the other tests functions in directory `tests`. Your tests should be located in `test_demand.py`.
- You could add the temperature that marks the heating period (in your case 15 °C) as a parameter again if you like - so that it's easier to select a different temperature.

2020-11-11 11:53 UTC, MaGering commented
> Thank you @MaGering for solving this issue!
> 
> * Could you add a docstring to your new function? There's a good example e.g. in `shift_working_hours()`.
> * Please add tests for `adjust_heat_demand()`. If you need examples you can look into the other tests functions in directory `tests`. Your tests should be located in `test_demand.py`.
> * You could add the temperature that marks the heating period (in your case 15 °C) as a parameter again if you like - so that it's easier to select a different temperature.


- [ ] Add a docstring to new function
- [ ] Add tests for `adjust_heat_demand()` located in `test_demand.py`
- [ ] Add limit temperature for heating period as input parameter so that it's easier to select a different temperature

2020-11-11 12:11 UTC, MaGering commented
>     * You could add the temperature that marks the heating period (in your case 15 °C) as a parameter again if you like - so that it's easier to select a different temperature.

So I would include it as an input parameter in building_parameters.csv?

2020-11-11 12:58 UTC, SabineHaas commented
> > ```
> > * You could add the temperature that marks the heating period (in your case 15 °C) as a parameter again if you like - so that it's easier to select a different temperature.
> > ```
> 
> So I would include it as an input parameter in building_parameters.csv?

At first I thought about `heat_pumps_and_chillers.csv` but maybe `building_parameters.csv` fits better! I don't have a preference. ;)

2020-11-12 00:32 UTC, MaGering commented
I extended the adjustment of the hourly heat demand in case warm water is included:

By setting the parameter `include_warm_water` to True, warm water is included in the calculations. In this case the hourly heat demand of space heating is separated from the hourly heat demand of warm water. The hourly heat demand of space heating **only** is then adjusted using `adjust_heat_demand(...)`. To finally obtain the total adjusted hourly heat demand the hourly heat demand of warm water **only** is added.

2020-11-12 00:42 UTC, MaGering commented
Here you can see an example plot of the adjusted hourly heat demand with and without warm water:

![Heat demand without warm water](https://user-images.githubusercontent.com/52790556/98880372-e4a2ee00-2487-11eb-9dd2-e11175d35ffb.png)
![Heat demand with warm water](https://user-images.githubusercontent.com/52790556/98880374-e53b8480-2487-11eb-891d-e987eb049dfc.png)

2020-11-12 14:57 UTC, SabineHaas requested changes
This is a very handy feature!

Could you add a test for `calculate_heat_demand()` where warm water is included please (once there's the option to in- or exclude it)?

2020-11-12 14:57 UTC, SabineHaas commented on pvcompare/demand.py
>          - electr_SH.at[country, str(year)]  #       - electr_WH.at[country, str(year)]
You can delete the comments now

2020-11-12 14:57 UTC, SabineHaas commented on pvcompare/demand.py
> +        - electr_WH.at[country, str(year)]  # - electr_WH.at[country, str(year)]
also here (comments)

2020-11-12 14:57 UTC, SabineHaas commented on pvcompare/demand.py
> +
```suggestion
```

2020-11-12 14:57 UTC, SabineHaas commented on pvcompare/demand.py
> +    include_warm_water = False  # Set true to include warm water
Could you add `include_warm_water` as a parameter of this function? and/or it could be a parameter in an input csv so that the user can choose. Does this make sense?

2020-11-12 14:57 UTC, SabineHaas commented on pvcompare/demand.py
> +    Adjust the hourly heat demand setting a limit to the temperature of heating
```suggestion
    Adjust the hourly heat demand setting a limit to the temperature of heating
    
```

2020-11-12 14:57 UTC, SabineHaas commented on tests/test_demand.py
> +        assert result.sum() == 10969639.113628691
```suggestion
        assert result.sum() == heat_load["kWh"].sum()
```
I think here you test, that the sum stays the same (because the load from summer times is distributed to the rest of the year). Could you also write a test that checks that expected values are set to zero please?

2020-11-13 11:03 UTC, MaGering commented on pvcompare/demand.py
>          - electr_SH.at[country, str(year)]  #       - electr_WH.at[country, str(year)]
Fixed with https://github.com/greco-project/pvcompare/pull/137/commits/c09bbce08c335434419b702f71a31961257f58a4

2020-11-13 11:03 UTC, MaGering commented on pvcompare/demand.py
> +        - electr_WH.at[country, str(year)]  # - electr_WH.at[country, str(year)]
Fixed with https://github.com/greco-project/pvcompare/pull/137/commits/c09bbce08c335434419b702f71a31961257f58a4

2020-11-13 11:52 UTC, MaGering commented on pvcompare/demand.py
> +    include_warm_water = False  # Set true to include warm water
Yes, it does! :)
Adapted with https://github.com/greco-project/pvcompare/pull/137/commits/06b0cb0fbc11ae55bd433157fab97d95d615c2b5

2020-11-13 17:29 UTC, MaGering commented
> Could you add a test for `calculate_heat_demand()` where warm water is included please (once there's the option to in- or exclude it)?

Done with commit https://github.com/greco-project/pvcompare/pull/137/commits/83284c8e51c4c3f4163b7e9dfb8728f469e68e61

2020-11-13 17:30 UTC, MaGering commented on tests/test_demand.py
> +        assert result.sum() == 10969639.113628691
Good idea! :)

Done with commit https://github.com/greco-project/pvcompare/pull/137/commits/289894fd4fa37b858f95664c1c21b6d0bda90064

2020-11-16 09:05 UTC, SabineHaas approved these changes

2020-11-17 09:26 UTC, c-moeller approved these changes

2020-11-17 09:35 UTC, Piranias approved these changes

2020-11-17 11:11 UTC, merged