Feature/add stratified tes
greco-project/pvcompare pull request #148
Opened 2020-11-18 17:54 UTC by MaGering

With this PR the stratified thermal energy storage is added to the sector coupling model. 

At present, in the mvs the oemof.solph component `GenericStorage` is defined with the following input parameters (cf. [D1_model_components.py](https://github.com/rl-institut/multi-vector-simulator/blob/5269b55562194275b5aab5ee253aeade1b655afb/src/multi_vector_simulator/D1_model_components.py#L540-L589)):

- label
- nominal_storage_capacity
- initial_storage_level
- loss_rate
- inflow_conversion_factor
- outflow_conversion_factor
- min_storage_level
- max_storage_level

To implement the oemof.thermal [stratified thermal storage](https://github.com/oemof/oemof-thermal/blob/dev/src/oemof/thermal/stratified_thermal_storage.py), two further input parameter would be needed (cf. example [01_operation_generic_storage.py](https://github.com/oemof/oemof-thermal/blob/eed5e8f0268d4b332e43078ad617c51327601b83/examples/stratified_thermal_storage/01_operation_generic_storage.py#L112-L128)):

- fixed_losses_relative
- fixed_losses_absolute
 
They are used to take into account temperature dependent losses of the storage.

The procedure within this PR is as follows:

- [ ] Implement basic structure containing "storage_02" as thermal energy storage with for now arbitrary input parameters
- [ ] Integrate pre-calculations of the stratified thermal storage from oemof.thermal into the model in a separate file called `stratified_thermal_storage.py`
- [ ] Write results for `nominal_storage_capacity` and `loss_rate` into `storage_02.csv` (`installedCap` and `efficiency`)
- [ ] Find a way to extend the model by the two additional parameters from oemof.thermal (`fixed_losses_relative` and `fixed_losses_absolute`)
- [ ] Research and adapt input parameters of the stratified thermal storage

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-01-12 19:07 UTC, MaGering commented
@c-moeller, @SabineHaas this PR is now ready for review.

To run the simulations with stratified thermal energy storage you'll need install mvs in your environment from your local repository and checkout the branch `feature/stratified_therm_storage_A1`, which belongs to this [PR](https://github.com/rl-institut/multi-vector-simulator/pull/718). There I have made the changes described in the bullet point above: 

> Find a way to extend the model by two additional parameters from oemof.thermal (`fixed_losses_relative` and `fixed_losses_absolute`)

2021-01-14 13:39 UTC, MaGering commented
I forgot to mention, that one thing is still missing: I wanted to implement a dependency of the `temp_high` parameters of the stratified TES and the heat pump so that the storage's temperature is adapted to the one of the heat pump. In order not to disturb your review and since this PR is already very extensive, I will do these changes within a new PR.

2021-01-14 15:15 UTC, SabineHaas reviewed
Wow this is a big PR, but it's great! 

My general comments:
- A test for `check_inputs.add_parameters_to_storage_xx_file()` would be nice. By the way, have you checked whether you could use `add_parameter_to_mvs_file()` instead?
- Please make sure that you test both options of adding a stratified thermal storage (directly to heat bus / via transformers). (did not check)
- I did not check the tests, yet, and would do that after you have worked on my comments.

2021-01-14 15:15 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +        os.path.join(user_inputs_mvs_directory, "csv_elements", storage_csv),
Additionally, this file cannot be read here, I think..? 
Firstly, because it does not exist for a use case without stratified thermal storage (like example inputs `mvs_inputs_electricity_sector`). Secondly, because here the stratified thermal storage, if existent, is not known, yet.

2021-01-14 15:15 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    )
Should this part (3. Replace...) maybe be done for all storages in `stratified_thermal_storages`?

2021-01-14 15:15 UTC, SabineHaas commented on tests/data/user_inputs/mvs_inputs/csv_elements/storage_02.csv
> +installedCap,NaN
Not totally sure, but I think `installedCap` should be None if it's not given as a number. But I'm never sure with the storage files, as some values should be `NaN' if not given..

2021-01-20 12:06 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +        os.path.join(user_inputs_mvs_directory, "csv_elements", storage_csv),
You're right! In order to read the filename from `energyStorage.csv`, I would need to implement something like this:

```
energy_storage.at["storage_filename", "storage_02"]
```

Now I've been thinking that placing `storage_02` there, leads to hardcoding the name of the stratified thermal storage. Should we maybe change `storage_02` to `storage_strat_tes` or something similar and add a check in the function whether this name exists or not. If not it would stop and print a message that no stratified thermal storage has been added.But in this case we would predefine the usage of a stratified thermal storage to `storage_strat_tes`. What do you think @SabineHaas?

2021-01-20 12:22 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +        os.path.join(user_inputs_mvs_directory, "csv_elements", storage_csv),
Or maybe I could try to obtain the name of the storage [here](In this case we wouldn't need to hardcode it as I mentioned before)?

2021-01-20 17:03 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +        os.path.join(user_inputs_mvs_directory, "csv_elements", storage_csv),
I would go for the second option as I think it would be nice if it's not hard coded.

2021-01-21 19:25 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    )
> Should this part (3. Replace...) maybe be done for all storages in `stratified_thermal_storages`?

This would be nice. But for now there is only one file `stratified_thermal_storage.csv`. Its parameters are used in the precalculations. So `storage_xx` does not change over different storages in `stratified_thermal_storages`. It's the same as with the heat pump. There as well we unfortunately can so far provide only one heat pump type in `heat_pumps_and_chillers.csv`. 🙁

2021-01-22 07:48 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    )
Ah I see.. well I think you should focus on finishing the implementation and on the simulations and this can be a "late issue" or nice-to-have!

2021-01-26 16:03 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +        os.path.join(user_inputs_mvs_directory, "csv_elements", storage_csv),
Done with commits https://github.com/greco-project/pvcompare/pull/148/commits/b681f36a5c0d56084252efaabd33b9eed76ab92c and https://github.com/greco-project/pvcompare/pull/148/commits/1b93813d6f71ee394cab31a7c2fa225d3a250fbf

2021-01-26 16:04 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +            stratified_thermal_storages.extend([col])
Done with commits https://github.com/greco-project/pvcompare/pull/148/commits/b681f36a5c0d56084252efaabd33b9eed76ab92c and https://github.com/greco-project/pvcompare/pull/148/commits/1b93813d6f71ee394cab31a7c2fa225d3a250fbf

2021-01-26 16:11 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +            inflow_tes = inflow
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/b681f36a5c0d56084252efaabd33b9eed76ab92c

2021-01-26 16:13 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    )
Good point! :)
Done for both parameters with commit https://github.com/greco-project/pvcompare/pull/148/commits/fc8e83cf2c7d5f69be659695432294ebbb96daeb. Test written in commit https://github.com/greco-project/pvcompare/pull/148/commits/2e71dc8a9050b14418e1ee69fa13805cd3429a1e.

2021-01-26 16:14 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    )
Thank you! 👍

2021-01-26 17:08 UTC, MaGering commented on tests/data/user_inputs/mvs_inputs/csv_elements/storage_02.csv
> +installedCap,NaN
Yes, I'm aware of this problem. However this results from the precalculations. If no height parameter of the storage is passed, then `installedCap` is `NaN` and so is the parameter written in the mvs input file.
It leads to the following warning in mvs:

```
WrongParameterWarning: In file storage_02.csv the parameter installedCap in column storage capacity is NaN. Please insert a value of 0 or int. For this simulation the value is set to 0 automatically.
  f"In file {filename}.csv the parameter {i}"
```
But because `installedCap`'s NaN is set to zero in mvs, the simulations work. I've tested it [here](https://github.com/rl-institut/multi-vector-simulator/blob/430ed9c932afb882c4dedb56d227defddb71a218/tests/test_benchmark_stratified_thermal_storage.py#L758-L854).

Do you think it is important to rework this?

2021-01-26 17:31 UTC, MaGering commented
> Wow this is a big PR, but it's great!

Thank you! I'm really glad you like it. I orientated strongly on the heat pump and chiller structure, which has already been implemented excellently by you! :)

>     * A test for `check_inputs.add_parameters_to_storage_xx_file()` would be nice. 

You're right! Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/2e71dc8a9050b14418e1ee69fa13805cd3429a1e

>  By the way, have you checked whether you could use `add_parameter_to_mvs_file()` instead?


Unfortunately I've seen this too late. But at first sight this function wouldn't do what we want, because it would overwrite the values each simulation, wouldn't it?

>     * Please make sure that you test both options of adding a stratified thermal storage (directly to heat bus / via transformers). (did not check)
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/7166e2ddab04a987812153fbe22600aa2a71e9f6

>     * I did not check the tests, yet, and would do that after you have worked on my comments.

👍

2021-01-27 07:52 UTC, SabineHaas commented on tests/data/user_inputs/mvs_inputs/csv_elements/storage_02.csv
> +installedCap,NaN
Ah nice, MVS solves this issue automatically! 
Nevertheless, I think it would be good if you adapt the parameter in pvcompare to 0, so that users don't stumble over the WrongParameterWarning. One might think that something needs to be changed otherwise.

2021-01-27 08:01 UTC, SabineHaas commented
> > By the way, have you checked whether you could use `add_parameter_to_mvs_file()` instead?
> 
> Unfortunately I've seen this too late. But at first sight this function wouldn't do what we want, because it would overwrite the values each simulation, wouldn't it?

It would overwrite a value in case the value in the csv differs from the value-to-be-added. 
Is that the same what `add_parameters_to_storage_xx_file()` does?

2021-01-28 14:35 UTC, MaGering commented
> It would overwrite a value in case the value in the csv differs from the value-to-be-added.
> Is that the same what `add_parameters_to_storage_xx_file()` does?

Ah and I thought this was exactly the difference: It should not be overwritten in case the user wants to pass those parameters herself or himself. For now I provided these two possibilities for the user:

- If you want `nominal storage capacity` and / or `efficiency` to be calculated, pass no value(s) (/ `NaN`).
- If you want to provide your own `nominal storage capacity` and / or `efficiency`, pass the value(s) with `storage_*.csv`.

I thought it gives the user more freedom handling the stratified thermal energy storage component. What do you think @SabineHaas? Of course I will need to document it well in `RTD`.

2021-01-28 14:38 UTC, SabineHaas commented
> > It would overwrite a value in case the value in the csv differs from the value-to-be-added.
> > Is that the same what `add_parameters_to_storage_xx_file()` does?
> 
> Ah and I thought this was exactly the difference: It should not be overwritten in case the user wants to pass those parameters herself or himself. For now I provided these two possibilities for the user:
> 
>     * If you want `nominal storage capacity` and / or `efficiency` to be calculated, pass no value(s) (/ `NaN`).
> 
>     * If you want to provide your own `nominal storage capacity` and / or `efficiency`, pass the value(s) with `storage_*.csv`.
> 
> 
> I thought it gives the user more freedom handling the stratified thermal energy storage component. What do you think @SabineHaas? Of course I will need to document it well in `RTD`.

oh yes, of course, sorry! I agree that the user should be able to define these values his/herself.

2021-01-28 16:14 UTC, MaGering commented on tests/data/user_inputs/mvs_inputs/csv_elements/storage_02.csv
> +installedCap,NaN
Yes, you're right! :) I adapted this and wrote a test. I pushed both with this commit https://github.com/greco-project/pvcompare/pull/148/commits/dead5edcefab0129170b796dc7d0f2f7b5384329.

2021-01-28 16:22 UTC, MaGering commented
>     * I did not check the tests, yet, and would do that after you have worked on my comments.

This PR is ready for your review now @SabineHaas. :)

There is one thing you'll have to watch out for: If you run the tests from your cloned mvs repo with `feature/stratified_therm_storage_A1` checked out, you'll have to add `minimal_degree_of_autonomy_factor,0` to `/tests/data/user_inputs/mvs_inputs/csv_elements/constraints.csv` as mentioned in the mvs issue https://github.com/rl-institut/multi-vector-simulator/issues/780 I created.

2021-02-05 11:25 UTC, SabineHaas requested changes
Thank you @MaGering! :)
I'm sorry, I still have some comments, but I think it's not so much work anymore!

- My overview over the directories we are using is not so good anymore, but I think `stratified_thermal_storage.csv` is missing in `data/user_inputs_collection/pvcompare_inputs/`.

2021-02-05 11:25 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    # Do precalculations for the stratified thermal storage
After having checked for stratified_thermal_storages above, all the following is not needed to be done if there is not stratified_thermal_storage, right?

2021-02-05 11:25 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    # Do precalculations for the stratified thermal storage
You could have an if statement like below `if len(stratified_thermal_storages) != 0:` for an easy solution

2021-02-05 11:25 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    # *********************************************************************************************
Also this part is only needed in case a TES exists..

2021-02-05 11:25 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +            heat_bus = bus
So, I think now, you only have option 1 (see docstring): TES is directly connected to heat bus. I think before you already had both options. 
If you only use this option for your simulations: To save time you could add a note to the docstring that 2) is not implemented and open an issue so that we don't forget about this in the future. (If you do that please copy+paste the code you had here before to help to find the solution, ask me if you don't know how to retrieve this part of the old code)

2021-02-08 10:23 UTC, MaGering commented on docs/parameters.rst
> +
Thank you @SabineHaas. The parameter `soc_max` had a typo in it. Plus I wrote it quite misleading. It's 15 % in total, which are unused.

I changed the wording and fixed `soc_max` in commit https://github.com/greco-project/pvcompare/pull/148/commits/cbfa652e09665bf11f7e2e68acdd9ee74ceae2f9.

2021-02-08 10:25 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    # Do precalculations for the stratified thermal storage
Absolutely! Thank you. :) Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/6e8d0937bc499001147890a93d33bb1ed563bac6.

2021-02-08 10:25 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    # *********************************************************************************************
Also done with commit https://github.com/greco-project/pvcompare/pull/148/commits/6e8d0937bc499001147890a93d33bb1ed563bac6.

2021-02-08 10:25 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +            heat_bus = bus
No, actually it works for both implementations. I realized the check from before was unnecessarily inflated. The common thing between both implementations is a bus with `Heat` as `energyVector`. In the first implementation TES is coupled directly to the `Heat bus` while in the second implementation there is an extra bus for the TES: `TES bus`. Both have `Heat` as `energyVector`. Now the clue is to check if `inflow_direction` and `outflow_direction` are same in `energyStorage.csv`. If `True` this component must be a thermal energy storage (TES). 

This however only works if the user has correctly implemented the stratified TES. If the `TES bus` for example is decoupled because the converter has been forgotten, precalculations will be done but will error out with a quite cryptic error message. Due to time restriction I did not write error interception for different ways of wrong implementations, since we explain in the docs how to implement the components correctly.


I've written a test to check the two ways of implementation [here](https://github.com/greco-project/pvcompare/blob/5b1c674970443a9fe4091bd8815a49625ca09f8e/tests/test_stratified_thermal_storage.py#L77-L271).

2021-02-08 10:28 UTC, MaGering commented
> Thank you @MaGering! :)
> I'm sorry, I still have some comments, but I think it's not so much work anymore!

No, I'm happy you have comments. Your review has helped me a lot, thank you! 🙏

>     * My overview over the directories we are using is not so good anymore, but I think `stratified_thermal_storage.csv` is missing in `data/user_inputs_collection/pvcompare_inputs/`.

Thanks for finding this! Added with commit https://github.com/greco-project/pvcompare/pull/148/commits/6a2e7450ad8b81bbf0f3bdb1de54699005290b2a.

2021-02-08 17:41 UTC, SabineHaas commented on docs/parameters.rst
> +
I still don't understand why it's 15 % in both max and min SOC.. Sorry, in case I just missed the point!

2021-02-08 17:42 UTC, SabineHaas commented on docs/parameters.rst
> +        b. **input power** and **output power**: 1 (this just means that the whole capacity of the stratified thermal storage would be used during charging and discharging cycles)
Have you checked whether the whole capacity actually can be charged/discharged during one cycle? Is one cycle in our case 1 hour?

2021-02-09 08:53 UTC, SabineHaas approved these changes
I made it through the tests now!  Only a few changes then you can merge :)

2021-02-09 08:53 UTC, SabineHaas commented on tests/test_stratified_thermal_storage.py
> +        results_abs_losses = [
I would include `exp` or `expected` in the name of the expected results, e.g. `exp_rel_losses`

2021-02-09 08:53 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +            heat_bus = bus
> No, actually it works for both implementations. I realized the check from before was unnecessarily inflated. The common thing between both implementations is a bus with `Heat` as `energyVector`. In the first implementation TES is coupled directly to the `Heat bus` while in the second implementation there is an extra bus for the TES: `TES bus`. Both have `Heat` as `energyVector`. Now the clue is to check if `inflow_direction` and `outflow_direction` are same in `energyStorage.csv`. If `True` this component must be a thermal energy storage (TES).

Oh nice, this is very neat! 



> I've written a test to check the two ways of implementation [here](https://github.com/greco-project/pvcompare/blob/5b1c674970443a9fe4091bd8815a49625ca09f8e/tests/test_stratified_thermal_storage.py#L77-L271).

I only meant to test the pvcompare function for the two ways of implementation. But your test even shows us that there's no difference in the simulations results for the two ways of implementation (when prices are set to zero) :+1:

2021-02-09 08:53 UTC, SabineHaas commented on tests/test_stratified_thermal_storage.py
> +    def test_calculate_losses_saved_file(self):
Is this test identical to the one above?

2021-02-09 08:53 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +):
Please add a docstring

2021-02-09 08:53 UTC, SabineHaas commented on tests/test_stratified_thermal_storage.py
> +            "fixed_thermal_losses_absolute_2017_53.2_13.2_95.0.csv",
So, this is the file that already exists and because of which no new file should be created. But how can you test here whether it is created or not, if the names are the same? If I understand right, in case a file would be created the name would be identical. So you actually need to use another file name and check that the file with the automatic file name does not exist.

2021-02-09 08:53 UTC, SabineHaas commented on tests/test_stratified_thermal_storage.py
> +    @classmethod
Here the classmethod, teardown_method and the fixture is the same as in the above class. Maybe you can have only one class for both functions (check whether teardown_method works as expected: deleting files between the tests within the class.)

2021-02-09 08:53 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +
Please add a one line statement (or more) stating what the function does.

2021-02-09 08:53 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    outflow_direction: "Heat").
```suggestion
    outflow_direction: "Heat"; check second option in the "Notes" section below).
```

2021-02-09 08:53 UTC, SabineHaas commented on pvcompare/stratified_thermal_storage.py
> +    'energyConversion.csv'.
It can only exist in energyStorage.csv

2021-02-09 08:53 UTC, SabineHaas commented on tests/test_stratified_thermal_storage.py
> +        sts.add_strat_tes(
Please name the test functions in the following pattern (you mostly do that):
`test_<name_of_function_that_is_tested>_<what_your_test_does>`

So here probably: `test_add_strat_tes_calculate_losses_saved_file`

2021-02-10 12:27 UTC, MaGering commented on docs/parameters.rst
> +
Ah ok! Sorry. That's a characteristic of the stratified thermal storage. The volume above and below of the inlet of the diffusors and the separation layer is not usuable. It has been implemented like this in oemof.thermal and according to this [source](https://op.europa.eu/en/publication-detail/-/publication/312f0f62-dfbd-11e7-9749-01aa75ed71a1/language-en). It is 15 % of the storage's volume. So your storage's capacity is reduced by 15 %. I assume for simplification that it is equally distributed above and below. Does this answer your question?

2021-02-11 08:46 UTC, SabineHaas commented on docs/parameters.rst
> +
Yes! Thank you! :) I think it would be clearer without having to check the source if you write
"7.5% unused volume " or even "7.5% unused volume on upper part of storage"
"7.5% unused volume on bottom part of storage"

2021-02-11 17:24 UTC, MaGering commented on docs/parameters.rst
> +        b. **input power** and **output power**: 1 (this just means that the whole capacity of the stratified thermal storage would be used during charging and discharging cycles)
That is a good question. I must confess I haven't dealt so far with the `c_rate` factor. In `oemof.solph` it's the parameters `invest_relation_input_capacity` and `invest_relation_output_capacity`.

In the data sheet of the storage, that I consider,

- charge and discharge efficiencies are 100 %
- energy storage capacity per unit (storage) is 3 kWh and
- input and output capacity for one unit (storage) are 20 kW.

Can I get the `c_rate` from these parameters?

2021-02-11 18:51 UTC, MaGering commented on tests/test_stratified_thermal_storage.py
> +        sts.add_strat_tes(
Perfect, thank you! :)
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/0195ba7fcbb921922771f06ade94f89f23cc00fb.

2021-02-11 18:53 UTC, MaGering commented on tests/test_stratified_thermal_storage.py
> +        results_abs_losses = [
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/0195ba7fcbb921922771f06ade94f89f23cc00fb.

2021-02-11 18:54 UTC, MaGering commented on tests/test_stratified_thermal_storage.py
> +    def test_calculate_losses_saved_file(self):
Oh right. Thank you. Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/0195ba7fcbb921922771f06ade94f89f23cc00fb.

2021-02-11 18:54 UTC, MaGering commented on tests/test_stratified_thermal_storage.py
> +    @classmethod
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/0195ba7fcbb921922771f06ade94f89f23cc00fb.

2021-02-15 12:06 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +):
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/faf87db59aad0593c86a8cd3e04ac13a8ebb7fe3.

2021-02-15 12:07 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/faf87db59aad0593c86a8cd3e04ac13a8ebb7fe3.

2021-02-15 12:07 UTC, MaGering commented on pvcompare/stratified_thermal_storage.py
> +    'energyConversion.csv'.
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/faf87db59aad0593c86a8cd3e04ac13a8ebb7fe3.

2021-02-15 12:07 UTC, MaGering commented on tests/test_stratified_thermal_storage.py
> +            "fixed_thermal_losses_absolute_2017_53.2_13.2_95.0.csv",
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/2c138ba35297784e3c93cd8ee7b11af0debc50fc.

2021-02-15 12:13 UTC, MaGering commented on docs/parameters.rst
> +
Done with commit https://github.com/greco-project/pvcompare/pull/148/commits/20715983fe0ff2b93c8ff90609671e09be309230.

2021-02-15 15:52 UTC, SabineHaas commented on docs/parameters.rst
> +        b. **input power** and **output power**: 1 (this just means that the whole capacity of the stratified thermal storage would be used during charging and discharging cycles)
hmm I really don't know. I would expect either a factor [0,1] or the amount of energy you can get from or add to the storage within one hour. 20 kW would be too much for one hour if the capacity is only 3 kWh..

2021-02-15 17:16 UTC, MaGering commented on docs/parameters.rst
> +        b. **input power** and **output power**: 1 (this just means that the whole capacity of the stratified thermal storage would be used during charging and discharging cycles)
I've opened a new issue on this topic. I'm going to merge this PR now and keep in mind to check the requirements for the `c_rate`.

2021-02-15 17:16 UTC, merged