Outputs/loop pvcompare
greco-project/pvcompare pull request #176
Opened 2020-12-11 19:57 UTC by Piranias

Fix  #172 #171

**Changes proposed in this pull request**:
- a new function "loop_pvcompare" is introduced in outputs.py.
- it is now possible to loop over pvcompare input parameters such as: location, year, storeys, technologies, hp_temp
- the input parameter "population" is replaces with "storeys", meaning the number of storeys of a house

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2020-12-22 09:37 UTC, Piranias commented on pvcompare/pv_feedin.py
> +        numver of storeys
```suggestion
        number of storeys
```

2020-12-30 12:44 UTC, MaGering requested changes
This are some very nice features. Thank you for implementing them! :)

Here are still further (potential) todos:
- If you run `outputs.py` from a newly cloned repository the output folder is missing.
- `run_pvcompare.py` has not been changed yet. It still contains the parameter population which should be replaced with storey.
- Existing time series cause that the loops in `outputs.py` don't not run as intended. Maybe deleting all time series before running mvs would be a safer solution (but will probably lead to a longer runtime).

2020-12-31 10:04 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
How would you like this to be automated? The function creates a single plot of all flows of one mvs output folder. So one has to specify which output folder they want to look at.

2020-12-31 10:11 UTC, Piranias commented on pvcompare/outputs.py
> +        step = 1
yes true, it was used before but then I changed it

2020-12-31 10:14 UTC, Piranias commented on pvcompare/outputs.py
> +
which one is the file containing the cops?

2020-12-31 10:29 UTC, Piranias commented on pvcompare/outputs.py
> +
the demand timeseries contain the number of storeys within their filename. So a new electricity demand is calculated if the time series does not exist already. Same for the pv timeseries which contain the location (lat, lon), the year and the technology in their name. I don't know how the cop timeseries is created (I have never used it). I would suggest to also include the temperature into the filename if this is the indicator. We could name all timeseries after the scheme:

technology_year_lat_lon_specific-attribute.csv

2020-12-31 10:38 UTC, Piranias commented on pvcompare/outputs.py
> +
small comment on this: I changed the heat demand to the scheme above. But it makes sense to leave the electricity demand with "country" because it's the same for all locations within a country.

2020-12-31 10:46 UTC, Piranias commented
>     * If you run `outputs.py` from a newly cloned repository the output folder is missing.

That's true, but is created automatically as soon as you run mvs.

2020-12-31 10:50 UTC, MaGering commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
We could have a further parameter `loop_type`, which contains the parameter you want to loop over and just one parameter `loop_dict` which contains the respective loop values using an if condition.

This is my suggestion for line 706 - 755:

```
    loop_type = "hp_temp"

    if loop_type == "storeys":
        loop_dict = {"start": 3, "stop": 5, "step": 1}
    elif loop_type == "technologies":
        loop_dict = {"step1": "cpv", "step2": "si", "step3": "psi"}
    elif loop_type == "hp_temp":
        loop_dict = {"start": 15, "stop": 25, "step": 5}

    # loop_pvcompare(
    #     scenario_name,
    #     latitude,
    #     longitude,
    #     year,
    #     storeys,
    #     country,
    #     loop_type=loop_type,
    #     loop_dict=loop_dict,
    #     mvs_input_directory=None,
    #     output_directory=None,
    #     input_directory=None,
    # )
    # loop_mvs(
    #     latitude=latitude,
    #     longitude=longitude,
    #     year=year,
    #     storeys=storeys,
    #     country=country,
    #     variable_name="specific_costs",
    #     variable_column="pv_plant_01",
    #     csv_file_variable="energyProduction.csv",
    #     start=500,
    #     stop=600,
    #     step=100,
    #     output_directory=output_directory,
    #     mvs_input_directory=mvs_input_directory,
    #     scenario_name=scenario_name,
    # )

    plot_all_flows(
        scenario_name=scenario_name,
        month=None,
        calendar_week=None,
        weekday=5,
        timeseries_directory=os.path.join(
            constants.DEFAULT_OUTPUT_DIRECTORY,
            scenario_name,
            "mvs_outputs_loop_" + loop_type + str(list(loop_dict.values())[0]),
        ),
    )
```

2020-12-31 10:54 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
We could of course think of another function for the loop, but then the output would need to look very different (I dont know how to plot all flows of multiple simulations within one plot..)

2020-12-31 10:56 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
ohh sorry I didn't mean to edit your comment!!

2020-12-31 12:52 UTC, MaGering commented on pvcompare/outputs.py
> +
It is the file `cops_heat_pump_<year>_<lat>_<lon>.csv` in `time_series`. It is created after the first loop and is not overwritten in the next loop.

2020-12-31 13:10 UTC, MaGering commented on pvcompare/outputs.py
> +
I see. However still something is wrong, because the electricity demand does not change. I observed the same output file `electricity_load_2014_Germany_5.csv` in all `time_series` loop folders (instead of `electricity_load_2014_Germany_3.csv`, `electricity_load_2014_Germany_4.csv` and `electricity_load_2014_Germany_5.csv`).

2020-12-31 13:15 UTC, MaGering commented on pvcompare/outputs.py
> +
I think I got the problem. Line 162 needs to look like this:

```
storeys=number_of_storeys,
```

2020-12-31 13:26 UTC, Piranias commented on pvcompare/outputs.py
> +
ahh right! Thank you for finding this!

2020-12-31 13:30 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
the plotting function is not only for loop outputs but for any mvs output. That's why this "automation" does not always make sense..

2020-12-31 13:31 UTC, Piranias commented on pvcompare/outputs.py
> +
so is the critical parameter the heat? then I would include it in the file name

2020-12-31 13:34 UTC, MaGering commented on pvcompare/outputs.py
> +
Yes, that would be great! Are you going to do this in this PR?

2020-12-31 13:44 UTC, MaGering commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
Okay! I guess I haven't seen these connections yet when I was testing the functions.
So what is the advantage or idea of / behind `plot_all_flows(...)`?

And how do you like the idea implementing this:

```
loop_type = "hp_temp"

    if loop_type == "storeys":
        loop_dict = {"start": 3, "stop": 5, "step": 1}
    elif loop_type == "technologies":
        loop_dict = {"step1": "cpv", "step2": "si", "step3": "psi"}
    elif loop_type == "hp_temp":
        loop_dict = {"start": 15, "stop": 25, "step": 5}

    # loop_pvcompare(
    #     scenario_name,
    #     latitude,
    #     longitude,
    #     year,
    #     storeys,
    #     country,
    #     loop_type=loop_type,
    #     loop_dict=loop_dict,
    #     mvs_input_directory=None,
    #     output_directory=None,
    #     input_directory=None,
    # )
```

and maybe commenting lines 729 - 739 with `plot_all_flows(...)` out to be consistent?

2020-12-31 13:46 UTC, Piranias commented on pvcompare/outputs.py
> +
yes I found this. But [here](https://github.com/greco-project/pvcompare/blob/280039c20fa8b9968eafd5978bb3870ea532f116/pvcompare/heat_pump_and_chiller.py#L239) it needs to be adapted as well, right?

2020-12-31 13:50 UTC, MaGering commented on pvcompare/outputs.py
> +
Yes that's right! :)

2020-12-31 13:51 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
so everything under >if __name__ == "__main__":< is just for trying out and testing. It is not meant to be used later on by any user. It will be deleted after all. (it's just handy to have testing functions ready while implementing). That's why I never bother to make this section clean, as it depends on your purpose what you want to test..

2020-12-31 13:54 UTC, Piranias commented on pvcompare/outputs.py
> +
I don't understand why the name of the file needs to be adapted there (and it's not possible to read in the temperature here or i don't know how). Can't we just check if the filename exists and otherwise, run calculate_cops_and_eers() ?

2020-12-31 13:54 UTC, MaGering commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
Oh I see. So the user won't work with loops? It is just for us? Or is he or she going to run these functions from `run_pvcompare.py`?

2020-12-31 13:58 UTC, Piranias commented on pvcompare/outputs.py
> +            "mvs_outputs_loop_hp_temp_15",
of course they can work with the loops. But the executing functions will be placed somewhere else, not in the modules scripts. That's why we have run_pvcompare for example. Or the user can write their own scripts. This " >if name == "main":< " is just for us right now.

2020-12-31 14:54 UTC, merged