New file structure
greco-project/pvcompare pull request #190
Opened 2020-12-31 15:03 UTC by Piranias

Fix #188 #180 #167 

**Changes proposed in this pull request**:
- completely new inputs structure
- new folder "examples"
- rework of the check_inputs.py module
- clean up the test repository

The following steps were realized, as well (if applies):
- [x] Use in-line comments to explain your code
- [x] Write docstrings to your code
- [:x:] For new functionalities: Explain in readthedocs
- [x] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [x] Apply black (`black . --exclude docs/`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-01-06 17:29 UTC, MaGering requested changes
Wow, this was indeed a huge task. Thank you for restructuring pvcompare! :)
Besides the comments I left, I have the following suggestions / corrections:

- Some of the tests in 
1. `test_cpv_perosi.py` and
2. `test_pv_feedin.py`
are failing.

-----------------------------------------------------------------------------

- project_data.csv is missing in: 

```
examples/example_user_inputs/mvs_inputs_electricity_sector/csv_elements/
pvcompare/data/user_inputs/mvs_inputs/csv_elements/
pvcompare/data/user_inputs_collection/mvs_inputs/csv_elements/
```
-----------------------------------------------------------------------------

- Is it possible to create an empty directory structure for user inputs ignoring their content in git?
  I thought about adding the following directories with .gitignore files in it:

```
  /pvcompare/data/user_inputs
	  .gitignore
  /pvcompare/data/user_inputs/mvs_inputs/
	  .gitignore
  /pvcompare/data/user_inputs/pvcompare_inputs
          .gitignore
```

An existing structure would simplify the handling of directories for the user. 
Otherwise, he or she must first create the structure uniquely to the one of the implementations      and this might be a bit confusing.

-----------------------------------------------------------------------------

-  `run_pvcompare_example_sector_coupling.py` is missing. Should I add it?

-----------------------------------------------------------------------------

- In line 109 of area_potential.py it supposed to be:

        storeys=5, user_inputs_pvcompare_directory="./data/inputs/", surface_type="flat_roof"

-----------------------------------------------------------------------------

-  The docs are depricated:

c.f. `basic_usage.rst` still contains the old parameters

-----------------------------------------------------------------------------

- The docstring of `calculate_cops_and_eers` in `heat_pump_and_chiller.py` contains old reference to directory

-----------------------------------------------------------------------------

- The docstring of `create_pv_components` in `pv_feedin.py` contains old reference to directory

-----------------------------------------------------------------------------

- For consistency reasons:

Change in `check_inputs.py`, `test_check_inputs.py`, `main.py` the following parameter:

	collections_mvs_input_directory  ->  collections_mvs_inputs_directory

And change in `test_cpv_perosi.py` and `test_heat_pump_and_chiller.py`
	
	mvs_input_directory -> mvs_inputs_directory

-----------------------------------------------------------------------------

2021-01-06 17:29 UTC, MaGering commented on pvcompare/outputs.py
> +        mvs_output_directoryoutput_directory=mvs_output_directory,
```suggestion
        mvs_output_directory=mvs_output_directory,
```

2021-01-06 17:29 UTC, MaGering commented on pvcompare/outputs.py
>          pv_setup=pv_setup,
```suggestion
        pv_setup=pv_setup,
        overwrite_grid_costs=False,
        overwrite_pv_parameters=True
```

It would not run without setting `overwrite_grid_costs=False`. If `True` I get a weird error:

```
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/outputs.py", line 725, in <module>
    user_inputs_pvcompare_directory=None,
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/outputs.py", line 175, in loop_pvcompare
    loop_type=loop_type,
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/outputs.py", line 264, in single_loop_pvcompare
    overwrite_pv_parameters=True
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/main.py", line 118, in apply_pvcompare
    user_inputs_mvs_directory=user_inputs_mvs_directory,
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/check_inputs.py", line 265, in add_electricity_price
    warning=True,
  File "/home/local/RL-INSTITUT/marie-claire.gering/test_pvcompare/pvcompare/pvcompare/check_inputs.py", line 509, in add_parameter_to_mvs_file
    if mvs_file.at[mvs_row, mvs_column] != pvcompare_parameter:
  File "/home/local/RL-INSTITUT/marie-claire.gering/miniconda3/envs/GRECO_env/lib/python3.7/site-packages/pandas/core/indexing.py", line 2270, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/local/RL-INSTITUT/marie-claire.gering/miniconda3/envs/GRECO_env/lib/python3.7/site-packages/pandas/core/frame.py", line 2767, in _get_value
    series = self._get_item_cache(col)
  File "/home/local/RL-INSTITUT/marie-claire.gering/miniconda3/envs/GRECO_env/lib/python3.7/site-packages/pandas/core/generic.py", line 3061, in _get_item_cache
    values = self._data.get(item)
  File "/home/local/RL-INSTITUT/marie-claire.gering/miniconda3/envs/GRECO_env/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 941, in get
    loc = self.items.get_loc(item)
  File "/home/local/RL-INSTITUT/marie-claire.gering/miniconda3/envs/GRECO_env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'DSO'
```

Is there a way to implement an interception at the location where `overwrite_grid_costs` is processed to avoid this error message?

2021-01-11 09:23 UTC, Piranias commented on examples/run_pvcompare_example_electricity_sector.py
> +outputs_directory = constants.EXAMPLE_DIRECTORY
It depends where you want the output to be. You should only set it to None if you want to use the default value. In this case I wanted the output to go into the example directory. So there would be a Scenario folder: pvcompare/examples/scenario_name. We could maybe also provide an empty output folder here, so that it is: pvcompare/examples/outputs/scenario_name

2021-01-11 09:25 UTC, MaGering commented on examples/run_pvcompare_example_electricity_sector.py
> +outputs_directory = constants.EXAMPLE_DIRECTORY
That (pvcompare/examples/outputs/scenario_name) sounds like a good plan! :)

2021-01-11 09:36 UTC, Piranias commented on pvcompare/main.py
> +    if mvs_output_directory is None:
this is tricky. So mvs_output_directory and outputs_directory is two different things. Here's what the two are:

outputs_directory = pvcompare/data/outputs
mvs_output_directory = pvcompare/data/outputs/scenario_name/mvs_outputs

so actually mvs_output_directory should never be constants.DEFAULT_OUTPUTS_DIRECTORY.

The parameter mvs_output_directory is actually only used for the loop (because the loop output name is defined within "outputs.mvs_loop()" and then given to "main.apply_mvs()". A user should not define this parameter because it is set up automatically with the output folder and the scenario name. So I will write a comment in the docstring about that.
Did this become clear?

2021-01-11 09:43 UTC, MaGering commented on pvcompare/main.py
> +    if mvs_output_directory is None:
Alright! It did, thank you. 

> So I will write a comment in the docstring about that.

This would be great! :)

2021-01-11 10:18 UTC, Piranias commented on pvcompare/outputs.py
>          pv_setup=pv_setup,
It's because you don't have the column "DSO" in your energyProvider.csv. Can you check if it's nessecary to allow different column names? (I mean, the energyPrice should only be set if a DSO is provided, so it makes sense to check weather it is a electricity DSO..)

2021-01-11 10:22 UTC, Piranias commented on pvcompare/outputs.py
>          pv_setup=pv_setup,
>     * Some of the tests in
>     1. `test_cpv_perosi.py` and
>     2. `test_pv_feedin.py`
>        are failing.

I don't see that they are failing, the build doesn't show any errors. Did you pull the last dev version and merge it? I added a feature for cpv a few days ago and merged it already. I'm pretty sure that's the reason.

2021-01-11 11:09 UTC, MaGering approved these changes
Looks good to me! :)

2021-01-11 12:22 UTC, merged

2021-01-13 09:44 UTC, Piranias commented on pvcompare/demand.py
> +        `constants.DEFAULT_USER_INPUTS_PVCOMPARE_DIRECTORY` is used as user_inputs_pvcompare_directory.
I would not change that, because the user only knows the parameter user_inputs_pvcompare_directory