Feature/Modelling different types of heat pumps and chillers
greco-project/pvcompare pull request #224
Opened 2021-02-05 20:48 UTC by MaGering

With this PR it is possible to model different types of heat pumps and chillers by adjusting their `temp_low` and `temp_high` parameters. A guidance can be found in the [documentation](https://github.com/greco-project/pvcompare/blob/feature/HP_gound_source/docs/heat_sector.rst) on this feature, which has also been written within this PR.

Summed up it basically enables the following on the example of a heat pump (chillers are handled analogously):

For the heat pump `temp_high` is the required parameter, while `temp_low` can be left empty. So the user has these possibilities of modelling the heat pump:

1. Constant target / outlet temperature `temp_high` and constant inlet temperature `temp_low` (eg. fix ground source heat pump with constant inlet temperature).
2. Constant target / outlet temperature `temp_high` and inlet temperature `temp_low` as time series, which the user herself provides (eg. fix ground source heat pump with changing inlet temperature).
3. Constant target / outlet temperature `temp_high` and inlet temperature `temp_low`, which is empty or equals `NaN`. In this case the ambient temperature is chosen (eg. fix air source heat pump).
4. Target / outlet temperature `temp_high` as time series, which the user herself provides and constant inlet temperature `temp_low` (eg. flexible ground source heat pump with constant inlet temperature).
5. Target / outlet temperature `temp_high` and inlet temperature `temp_low` as time series, which the user herself provides (eg. flexible ground source heat pump with changing inlet temperature).

An error is raised if `temp_high` is missing.

I've written test to check the functionality of all of these cases.

The following steps were realized, as well (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code
- :x: Update the CHANGELOG.md (let's start this after the first release)
- [ ] Apply black (`black . --exclude docs/`)
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Check not applicable to this PR

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-02-09 16:48 UTC, SabineHaas requested changes
Nice that you also worked on the documentation! :) 

- Does this solve #210? Then you can add "Fix #210" at the top of the PR message, which will close the issue automatically after merge.

- I'm not sure whether using a lot of try-except statements are a good coding practice. I know I have used this in a function for the heat pump but I think using them extensively (maybe also the way I have used them) is not recommended. When asking PF about that he send me the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) saying "Explicit is better than implicit." Also, using if statements would be easier to read. You can consider that but if try-except seems to be the better solution for you, you can leave them of course.

2021-02-11 11:30 UTC, MaGering commented on pvcompare/heat_pump_and_chiller.py
> +        temperature : float
I think I've seen "numeric" in other docstring also with `pd.Series` as possible type. But I think yours is more exact. Thank you! :)

2021-02-11 11:54 UTC, MaGering commented on docs/heat_sector.rst
> +You can also provide your own time series of temperatures in a separate file as shown in this example:
Do you mean a constant low temperature at one value? That's a tough one. I've assumed that this case is defined as ground source heat pump since the air temperature varies over time. What do you think?

2021-02-11 13:49 UTC, SabineHaas commented on docs/heat_sector.rst
> +You can also provide your own time series of temperatures in a separate file as shown in this example:
Ah yes, you're right. From the modelling point of view it's possible to use a constant COP if a user does not wish to use the calculations of oemof-thermal, but it does not make sense to do that; so better not give the idea :P

2021-02-11 17:06 UTC, MaGering commented on docs/heat_sector.rst
> +while passing **temp_high**, **factor_icing** and **temp_threshold_icing** are optional.
Yes, you're right! They don't apply. And I also now realized, that describing the modeling of a chiller is misleading. I thought I used it recently in a simulation. But when I tried today, the simulation would error out. Should I maybe take the section `Chiller` out from `heat_sector.rst` and write that so far it is not possible to run the simulations with a chiller?

2021-02-11 17:07 UTC, MaGering commented on docs/heat_sector.rst
> +(In this example temperatures are provided in ``temperature_heat_pump.csv``. The file's header is *degC*.)
Done in commit https://github.com/greco-project/pvcompare/pull/224/commits/462df6cd872323d1edd92504b90c425babb2d1ff.

2021-02-11 17:08 UTC, MaGering commented on pvcompare/heat_pump_and_chiller.py
> +        ("chiller") are calculated. Default: "heat_pump".
Solved in commit https://github.com/greco-project/pvcompare/pull/224/commits/484ae91c58772d9de9a08e7a35593d54c15f1bbe.

2021-02-11 17:16 UTC, MaGering commented
> Nice that you also worked on the documentation! :)
> 
>     * Does this solve #210? Then you can add "Fix #210" at the top of the PR message, which will close the issue automatically after merge.

Unfortunately not. It is possible to model different types of heat pumps but you can't combine these types in one simulation. For example an air-to-air heat pump **and** a brine-water heat pump in one simulation.
> 
>     * I'm not sure whether using a lot of try-except statements are a good coding practice. I know I have used this in a function for the heat pump but I think using them extensively (maybe also the way I have used them) is not recommended. When asking PF about that he send me the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) saying "Explicit is better than implicit." Also, using if statements would be easier to read. You can consider that but if try-except seems to be the better solution for you, you can leave them of course.

Oh, [Zen of Python](https://www.python.org/dev/peps/pep-0020/) made my day! 😆
I adapted the code, making it more explicit where I could. See commit https://github.com/greco-project/pvcompare/pull/224/commits/120747f9f7cb6aac2e28056cd7f9d8fcd0a5c8fa. All checks have passed with the adaptations.

2021-02-11 17:41 UTC, SabineHaas commented on docs/heat_sector.rst
> +while passing **temp_high**, **factor_icing** and **temp_threshold_icing** are optional.
You could add a warning in front of the section with `.. warning::` then we don't loose the text and if we have time in the end we can make the  chiller possible.

2021-02-11 17:43 UTC, MaGering commented on docs/heat_sector.rst
> +while passing **temp_high**, **factor_icing** and **temp_threshold_icing** are optional.
Sounds like a good plan! :) Will do that.

2021-02-11 17:44 UTC, SabineHaas approved these changes

2021-02-11 18:04 UTC, MaGering commented on docs/heat_sector.rst
> +while passing **temp_high**, **factor_icing** and **temp_threshold_icing** are optional.
Done in commit https://github.com/greco-project/pvcompare/pull/224/commits/4977cae37fdb1444287cb328a5662984265d0349.

2021-02-11 18:08 UTC, merged