Feature/improve rtd
greco-project/pvcompare pull request #291
Opened 2021-04-21 17:02 UTC by MaGering

Fix Issue https://github.com/greco-project/pvcompare/issues/157 and improve RTD

With this PR the RTD section `Model assumptions` is improved by adjusting the description of the heat demand.
Further a description of the stratified thermal storage is added.

The following steps were realized, as well (required):
- [ ] Update the CHANGELOG.md
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

Also the following steps were realized (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

In case of an error due to linting, run `black . --exclude docs/` and push your changes.
Note that in case you do not fix a whole issue you should start your PR with `Address #xyz`.

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-04-21 17:05 UTC, MaGering commented
As I already told you @SabineHaas I have problems rendering the image docs/images/input_timeseries_Heat demand_shww.png
 
The section `Stratified thermal storage` is not complete yet, but feel free to correct and leave comments there already.

I think I will resolve the RTD bullet point in issue https://github.com/greco-project/pvcompare/issues/290 within a separate PR. Do you agree?

2021-04-22 07:53 UTC, SabineHaas requested changes
@MaGering , I did not fully read through the storage section, yet (will do so when PR is ready for review). In total it looks very good to me. I mainly corrected typos and added links. 

Thank you for improving the documentation :)

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +*pvcompare*'s input file ``building_parameters.csv`` is set to ``True``.
```suggestion
*pvcompare*'s input file :ref:`building_parameters` is set to ``True``.
```
like this there's a link to the [parameter section](https://pvcompare.readthedocs.io/en/latest/parameters.html#building-parameters-csv)

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +``building_parameters.csv``. In case of space heating, heat demand during summer is removed if
```suggestion
:ref:`building_parameters`. In case of space heating, heat demand during summer is removed if
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +an approximation.
However, it is adapted for multiple countries by [hour shifting](https://github.com/greco-project/pvcompare/blob/50c4740c52e826bf6b40f9eee49bf1c69f44ef4e/pvcompare/demand.py#L562)

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +``building_parameters.csv``. In case of space heating, heat demand during summer is removed if
You could add "and is by default X."

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +the daily mean temperature crosses the the heating limit temperature. The excess heat demand is
```suggestion
the daily mean temperature exceeds the heating limit temperature. The excess heat demand is
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +then distributed equally over the remaining heat demand. In case of a heat demand from space
```suggestion
then distributed equally over the remaining time of the year. In case of a heat demand from space
```
if that's better..

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +heating and warm water only the heat demand of the space heating is adjusted as described above.
```suggestion
heating and warm water, only the heat demand of the space heating is adjusted as described above.
```
I'm not good in setting commas, but I first understood "space heating and warm water only, the heat demand ..." to maybe it's good to set a comma

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +population. The annual heat demand for space heating and warm water is calculated by the
```suggestion
population, which is derived from the given number of houses and storeys (for assumptions see :ref:`building_assumptions`). The annual heat demand for space heating and warm water is calculated by the
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +1)  the residential heat demand for a country is requested from `EU Building Database <https://ec.europa.eu/energy/en/eu-buildings-database#how-to-use>`_.
```suggestion
1)  the residential heat demand for a country is taken from the `EU Building Database <https://ec.europa.eu/energy/en/eu-buildings-database#how-to-use>`_.
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +1)  the residential heat demand for a country is requested from `EU Building Database <https://ec.europa.eu/energy/en/eu-buildings-database#how-to-use>`_.
maybe a better word than "taken" - but "requested" sounds like a request runs every time.

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
>  2)  on the lines of the electricity demand, the population of the country is requested from `EUROSTAT <https://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&plugin=1&language=en&pcode=tps00001>
Also here "requested" is not the right word. Could you adapt that in the electricity section, as well, please?

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
>  3)  the total residential demand is divided by the countries population and
```suggestion
3)  the total residential demand is divided by the country's population and
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
>      multiplied by the house population that is calculated by the storeys
Could you please adapt this sentence here and in electricity section? Maybe better: 
"the total residential demand is divided by the country's population and multiplied by the population (for assumptions see :ref:`building_assumptions`)"

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +an approximation.
ah yes, see point 4 (maybe a little hint here?)

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +can be obtained, if not provided, orientating on the stratified thermal storage component
```suggestion
can be obtained, if not provided by the user, orientating on the stratified thermal storage component
```

2021-04-22 07:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +``stratified_thermal_storage.csv`` which is located in the *pvcompare*'s iputs directory:
you could add a link to stratified_thermal_storage.csv, and maybe state that the parameters are explained there  + default values and references are given.

2021-04-22 07:53 UTC, SabineHaas commented
> As I already told you @SabineHaas I have problems rendering the image docs/images/input_timeseries_Heat demand_shww.png

Fixed with 7e580f2 , however the RTD build of this PR did not change. I therefore activated the branch on RTD: https://pvcompare.readthedocs.io/en/feature-improve-rtd/model_assumptions.html#heat-demand

> 
> The section `Stratified thermal storage` is not complete yet, but feel free to correct and leave comments there already.
> 
> I think I will resolve the RTD bullet point in issue #290 within a separate PR. Do you agree?

what do you mean by RTD bullet point?

2021-04-22 08:35 UTC, MaGering commented on docs/model_assumptions.rst
> +heating and warm water only the heat demand of the space heating is adjusted as described above.
You're absolutely right with the comma. Thank you! :)

2021-04-22 12:53 UTC, MaGering commented on docs/model_assumptions.rst
> +an approximation.
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/87f85c86b5c53b0b48f8b045f4a89f3c5fb0ec7f.

2021-04-22 12:54 UTC, MaGering commented on docs/model_assumptions.rst
>  2)  on the lines of the electricity demand, the population of the country is requested from `EUROSTAT <https://ec.europa.eu/eurostat/tgm/table.do?tab=table&init=1&plugin=1&language=en&pcode=tps00001>
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/87f85c86b5c53b0b48f8b045f4a89f3c5fb0ec7f.

2021-04-22 12:54 UTC, MaGering commented on docs/model_assumptions.rst
> +``building_parameters.csv``. In case of space heating, heat demand during summer is removed if
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/87f85c86b5c53b0b48f8b045f4a89f3c5fb0ec7f.

2021-04-22 12:56 UTC, MaGering commented on docs/model_assumptions.rst
>      multiplied by the house population that is calculated by the storeys
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/87f85c86b5c53b0b48f8b045f4a89f3c5fb0ec7f.

Could you please check if `3)` is okay like that now?

2021-04-22 12:57 UTC, MaGering commented on docs/model_assumptions.rst
> +``stratified_thermal_storage.csv`` which is located in the *pvcompare*'s iputs directory:
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/87f85c86b5c53b0b48f8b045f4a89f3c5fb0ec7f.

2021-04-22 12:59 UTC, MaGering commented
> what do you mean by RTD bullet point?

Ah sorry. :-D 
I meant this task in PR https://github.com/greco-project/pvcompare/issues/290: 

```
the documentation in Model assumptions needs to be updated in both sections Electricity demand and Heat demand
```

2021-04-22 13:46 UTC, SabineHaas approved these changes
only minor changes required before merging :)

2021-04-22 13:46 UTC, SabineHaas commented on docs/model_assumptions.rst
> +    and multiplied by the population. The population is calculated by the product of the
ahh sorry now something is missing behind population :D 
```suggestion
    and multiplied by the population living in the area considered. The latter is calculated by the product of the
```

2021-04-22 13:46 UTC, SabineHaas commented on docs/model_assumptions.rst
> +    and multiplied by the population. The population is calculated by the product of the
```suggestion
    and multiplied by the population living in the area considered. The latter is calculated by the product of the
```

2021-04-22 13:46 UTC, SabineHaas commented on docs/model_assumptions.rst
> +5)  The load profile is shifted due to countries specific behaviour following the
```suggestion
5)  For multiple countries, the load profile is adapted by hour shifting following the
```

2021-04-22 13:46 UTC, SabineHaas commented on docs/model_assumptions.rst
> +function calculate_losses(...) of *oemof.thermal*. Please see the
(...) is missing

2021-04-22 13:46 UTC, SabineHaas commented on docs/model_assumptions.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Could you shortly explain what relative and absolute means here?

2021-04-22 14:16 UTC, MaGering commented on docs/model_assumptions.rst
> +function calculate_losses(...) of *oemof.thermal*. Please see the
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/b41304b13a8d8c372c58acdd7869e7840b2eea68.

2021-04-22 14:16 UTC, MaGering commented on docs/model_assumptions.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Done with commit https://github.com/greco-project/pvcompare/pull/291/commits/b41304b13a8d8c372c58acdd7869e7840b2eea68.

2021-04-22 15:11 UTC, merged