[Dokumentation] Update parameters/basic_usage/model_assumptions
greco-project/pvcompare pull request #302
Opened 2021-05-04 14:17 UTC by Piranias

Fix #106 #290 #277 #76 #165

**Changes proposed in this pull request**:
- Your_changes

The following steps were realized, as well (required):
- [ ] Update the CHANGELOG.md
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

Also the following steps were realized (if applies):
- [ ] Use in-line comments to explain your code
- [ ] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

In case of an error due to linting, run `black . --exclude docs/` and push your changes.
Note that in case you do not fix a whole issue you should start your PR with `Address #xyz`.

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-05-05 09:53 UTC, MaGering requested changes
Thanks for the changes! So nice that you also updated the parameters section. :)

I made my comments and propositions of changes here on GitHub in files changed mode. I think it will be necessary to build the documentation in order to see if the formatting is alright after applying the review changes because I didn't check that.

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    15. **emission_factor**: kgCO2eq/unit, * *auto_calc*
```suggestion
    15. **emission_factor**: kgCO2eq/unit, * *auto_calc*
    16. **renewableAsset**: bool, True (for all of the components)
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +All default values for the energy_price, feed-in tariff, renewable share and emission factors of all European countries are stores in
```suggestion
All default values of the energy price, feed-in tariff, renewable share and emission factor of European countries are stored in
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +        a. **Electricity grid**: `feed-in tariff <https://www.pv-magazine.com/features/archive/solar-incentives-and-fits/feed-in-tariffs-in-europe/>`_
```suggestion
        a. **Electricity grid**: * *auto_calc* `feed-in tariff <https://www.pv-magazine.com/features/archive/solar-incentives-and-fits/feed-in-tariffs-in-europe/>`_
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    7. **renewable_share**,factor,`EUROSTAT renewable share <https://ec.europa.eu/eurostat/web/energy/data/shares>`_
```suggestion
    7. **renewable_share**,factor, * *auto_calc* `EUROSTAT renewable share <https://ec.europa.eu/eurostat/web/energy/data/shares>`_
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +        a. **Electricity grid**: `EEA EUROPA <https://www.eea.europa.eu/data-and-maps/indicators/overview-of-the-electricity-production-3/assessment>`_
```suggestion
        a. **Electricity grid**: * *auto_calc* `EEA EUROPA <https://www.eea.europa.eu/data-and-maps/indicators/overview-of-the-electricity-production-3/assessment>`_
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +        b. **input power** and **output power**: 0.95 (Charging and discharging efficiency. The value has been sourced from `MVS efficiency <https://multi-vector-simulator.readthedocs.io/en/stable/MV
```suggestion
    10. **efficiency**: factor
    
        a. **storage capacity**: 0.95
        
        b. **input power** and **output power**: 0.95 (Charging and discharging efficiency. The value has been sourced from `MVS efficiency <https://multi-vector-simulator.readthedocs.io/en/stable/MVS_parameters.html#efficiency-label>`_.)
```

I don't know why rtd doesn't apply new lines here. So let's try maybe this...

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
>      11. **soc_initial**: None or factor
Here also the lines were inserted to have a new line. So maybe revert the deletions?

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
>          b. **input power** and **output power**: NA
```suggestion

        a. **storage capacity**: 0.98 ( `Solar charge controllers <https://www.morningstarcorp.com/solar-charge-controllers>`_)
        
        b. **input power** and **output power**: NA
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +        a. **storage capacity**: 0.95
This value is 1 in user inputs collections. Please check.

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +        a. **storage capacity**: 0.15 (Figure from this research `article <https://www.sciencedirect.com/science/article/pii/S0378775319310043>`_.)
This value is 0.2 in user inputs collections. Please check.

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    10. **include warm water**: bool, False (condition about whether warm water is considered in the heat demand, default: False. If False, the warm water demand is added to the electricty demand ins
```suggestion
    10. **include warm water**: bool, False (condition about whether warm water is considered in the heat demand, default: False. If False, the warm water demand is neglected in the simulation.)
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption for EU countries from [2]) *
Actually we don't need this anymore I think. Should we take it out of pvcompare inputs?

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption for EU countries from [2]) *
```suggestion
    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption of countries in the European Union from [2]) *
```

2021-05-05 09:53 UTC, MaGering commented on docs/parameters.rst
> +    19. **filename_country_population**: str ,EUROSTAT_population.csv (name of the csv with total population per country [2])
```suggestion
    12. **filename_total_SH**: str, total_consumption_SH_residential.xlsx (name of the csv file that contains the total energy consumption for space heating of countries in the European Union [2]) *
    13. **filename_total_WH**: str, total_consumption_WH_residential.xlsx (name of the csv file that contains the total energy consumption for water heating of countries in the European Union [2]) *
    14. **filename_elect_SH**: str, electricity_consumption_SH_residential.xlsx (name of the csv file that contains the electrical energy consumption of space heating of countries in the European Union countries [2]) *
    15. **filename_elect_WH**: str, electricity_consumption_WH_residential.xlsx (name of the csv file that contains the electrical energy consumption of warm water heating of countries in the European Union [2]) *
    16. **filename_residential_electricity_demand**: str, electricity_consumption_residential.xlsx (name of the csv file that contains the total electricity energy consumption in residential sector of countries in the European Union [2]) *
    17. **filename_total_cooking_consumption**: str, total_consumption_cooking_residential.xlsx (name of the csv file that contains the total energy consumption for cooking in residential sector of countries in the European Union [2])
    18. **filename_electricity_cooking_consumption**: str,electricity_consumption_cooking_residential.xlsx (name of the csv file that contains the electrical residential cooking demand of countries in the European Union [2])
    19. **filename_country_population**: str, EUROSTAT_population.csv (name of the csv file with total population of each country in the European Union [2])
```

2021-05-05 10:21 UTC, MaGering commented on docs/parameters.rst
> +    4. **lifetime**: year, 20 (for all components), `Moosmoar S.3<https://iewt2019.eeg.tuwien.ac.at/download/contribution/presentation/112/112_presentation_20190215_102253.pdf>`_
```suggestion
    4. **lifetime**: year, 20 (for all components), `Moosmoar S.3 <https://iewt2019.eeg.tuwien.ac.at/download/contribution/presentation/112/112_presentation_20190215_102253.pdf>`_
```

2021-05-05 17:11 UTC, Piranias commented on docs/parameters.rst
> +    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption for EU countries from [2]) *
what do you mean?

2021-05-05 17:14 UTC, MaGering commented on docs/parameters.rst
> +    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption for EU countries from [2]) *
The file `total_consumption_residential.xlsx`. I think we don't use it anymore in the calculations do we?

2021-05-05 17:17 UTC, Piranias commented on docs/parameters.rst
> +    11. **filename_total_consumption**: str, total_consumption_residential.xlsx (name of the csv file that contains the total electricity and heat consumption for EU countries from [2]) *
ah interesting. I think you're right. But then we should also delete it from "building_parameters"..
I'll do that

2021-05-05 17:41 UTC, Piranias commented on docs/parameters.rst
>      11. **soc_initial**: None or factor
hmm when I create the html's locally everything looks fine also without inserting blank lines..

2021-05-06 08:14 UTC, MaGering approved these changes
Could you maybe move the `*` comment to the bottom of the page? It is somehow mixed with the references:

```
[5] Beikircher, Thomas & Buttinger, Frank & Rottmann, Matthias & Herzog, Fabian & Konrad, Martin & Reuß, Manfred & Beikircher, Redaktion, 2013: Superisolierter Heißwasser-Langzeitwärmespeicher : Abschlussbericht zu BMU-Projekt Förderkennzeichen 0325964A, Projektlaufzeit: 01.05.2010 - 31.10.2012. 10.2314/GBV:749701188.
\* the described csv files are to be added to the input folder accordingly.
[6] In:Klan, H, 2002: Wärmeübergang durch freie Konvektion an umströmten Körpern. Berlin, Heidelberg: Springer Berlin Heidelberg, ISBN 978-3-662-10743-0, 567-591
```

And also not every input file in buildings_parameters.csv has the `*`.

2021-05-06 08:14 UTC, MaGering commented on CHANGELOG.md
> +- Dokumentation: Update on 'basic_usage', 'parameter description' and 'model assumptions' (#106 #290 #277 #76 #165)
I think here we add PR number not issue number, don't we?

```suggestion
- Dokumentation: Update on 'basic_usage', 'parameter description' and 'model assumptions' (#302)
```

2021-05-06 08:14 UTC, MaGering commented on docs/parameters.rst
> +    * list of countries for which a python.workalendar [3] exists with the column name "country".*
```suggestion
    *list of countries for which a python.workalendar [3] exists with the column name "country".* *
```

In consistency with the layout of the others.

2021-05-06 10:53 UTC, SabineHaas requested changes
Nice @Piranias thanks for filling our docs!

It would be nice to have links for the directories, like examples, or files like run_pvcompare.py, to github. But this could also be a task for a supporter when reading our RTD --> please make a note or open issue.

2021-05-06 10:53 UTC, SabineHaas commented on docs/basic_usage.rst
> +If you run a simulation, *pvcompare* automatically downloads the ERA5 weather data from `Climate Data Store (CDS) <https://cds.climate.copernicus.eu/>`_ and store it locally in ``data/static_inputs``
```suggestion
If you run a simulation, *pvcompare* automatically downloads the ERA5 weather data from `Climate Data Store (CDS) <https://cds.climate.copernicus.eu/>`_ and stores it locally in ``data/static_inputs``, unless the
```

2021-05-06 10:53 UTC, SabineHaas commented on docs/basic_usage.rst
> +file already exists. In order to enable this download you first need to make an account at the `CDS <https://cds.climate.copernicus.eu/user/login?destination=%2F%23!%2Fhome>`_ and
```suggestion
file already exists. In order to enable this download you first need to create an account at the `CDS <https://cds.climate.copernicus.eu/user/login?destination=%2F%23!%2Fhome>`_ and
```

2021-05-06 10:53 UTC, SabineHaas commented on docs/basic_usage.rst
> +install the cdsapi package. `This page <https://cds.climate.copernicus.eu/api-how-to>`_ provides information about the installation. When using the API for a large amount of data (e.g. a year for one
```suggestion
install the *cdsapi* package. `This page <https://cds.climate.copernicus.eu/api-how-to>`_ provides information about the installation. When using the API for a large amount of data (e.g. a year for one location) the request gets queued and the download might take a while.
```

2021-05-06 10:53 UTC, SabineHaas commented on docs/basic_usage.rst
> +
Do we provide example weather data? then you could state this here, as well.

2021-05-06 10:53 UTC, SabineHaas commented on docs/basic_usage.rst
> +todo: add more information here (IS)
please remove todo and open issue or add to #106 and don't close it with this pr

2021-05-06 10:53 UTC, SabineHaas commented on docs/model_assumptions.rst
> +.. warning:: It is currently not possible to model these two demands separately with two heat demand profiles and, for example, to use different technologies to cover the respective demand. Contribut
Could you write an issue on what more or less has to be done/considered when implementing this and link it here? This would be helpful for contributors

2021-05-06 10:53 UTC, SabineHaas commented on run_pvcompare.py
> +scenario_name = "Scenario_Test"
```suggestion
scenario_name = "My_Scenario"
```
?

2021-05-06 10:53 UTC, SabineHaas commented on run_pvcompare.py
> +# the following values are only example values
```suggestion
# the following parameters are needed to run pvcompare, you can adapt them to your needs
```

2021-05-10 09:25 UTC, Piranias commented on docs/model_assumptions.rst
> +.. warning:: It is currently not possible to model these two demands separately with two heat demand profiles and, for example, to use different technologies to cover the respective demand. Contribut
@MaGering , can you do this?

2021-05-10 09:28 UTC, Piranias commented on docs/basic_usage.rst
> +
right now we don't. But I could add the one for Berlin, 2017 that is used in the examples.

2021-05-11 16:12 UTC, MaGering commented on docs/model_assumptions.rst
> +.. warning:: It is currently not possible to model these two demands separately with two heat demand profiles and, for example, to use different technologies to cover the respective demand. Contribut
Yes! I added a reference to Issue https://github.com/greco-project/pvcompare/issues/311 [here](https://github.com/greco-project/pvcompare/pull/302/files#r630326059).

2021-05-12 06:21 UTC, SabineHaas approved these changes
hi @Piranias only two more suggestions

2021-05-12 06:21 UTC, SabineHaas commented on docs/basic_usage.rst
> +You can configure your own scenario by defining the parameters in ``data/user_inputs``. It contains two subfolders ``mvs_inputs`` for all MVS parameters and ``pvcompare_inputs`` for *pvcompare* input
Does `main()` still exist? The link does not work

2021-05-12 06:21 UTC, SabineHaas commented on docs/basic_usage.rst
> +**pvcompare_inputs**
I think you need an empty line here to make the list work --> https://pvcompare--302.org.readthedocs.build/en/302/basic_usage.html#define-your-own-components-and-parameters
```suggestion
**pvcompare_inputs**

```

2021-05-12 08:57 UTC, merged