Change docstring of demand.py
greco-project/pvcompare pull request #309
Opened 2021-05-11 13:56 UTC by Stefanie08

Address #303 

**Changes proposed in this pull request**:
- Docstrings were reviewed
- parameters added 
- harmonized format

The following steps were realized, as well (required):
- [ ] Update the CHANGELOG.md
- [ ] Check if full simulation tests pass locally (`EXECUTE_TESTS_ON=master pytest`)

Also the following steps were realized (if applies):
- [ ] Use in-line comments to explain your code
- [x] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code

*Please mark above checkboxes as following:*
- [x] Open
- [ ] Done

In case of an error due to linting, run `black . --exclude docs/` and push your changes.
Note that in case you do not fix a whole issue you should start your PR with `Address #xyz`.

<sub>*For more information on how to contribute check the [CONTRIBUTING.md](https://github.com/rl-institut/mvs_eland/blob/dev/CONTRIBUTING.md).*<sub>

2021-05-11 14:51 UTC, SabineHaas reviewed
Thank you @Stefanie08 ! 

I made some suggestions that you can accept via "add suggestion to badge" and then commit them (I think only from "Files changed" tab).

And some more points to finalize the PR:
- [x] To track the changes we always state our changes `CHANGELOG.md`. You can add a sentence like "Improved docstrings of functions in `demand.py` (#309)" - the number is the number of your PR. 
In the following PRs for addressing #303 you can then just add further modules and PR numbers.

- [ ] I haven't told you about `black`, yet. It checks our code linting, also the docstrings. To make the first check of this PR pass you should write the line `black . --exclude docs/` and push your changes. This will adapt the code style to a specific format. You have to take care to install the same black version as given in setup.py.
- [x] Is the file `Data.csv` necessary? If not, please delete.

- [ ] Please adapt everywhere:
```
static_inputs_directory: str or None
    Directory of the pvcompare static inputs. If None,
    `constants.DEFAULT_STATIC_INPUTS_DIRECTORY` is used.
    Default: None.
user_inputs_pvcompare_directory: str or None
    Path to user input directory. If None,
    `constants.DEFAULT_USER_INPUTS_PVCOMPARE_DIRECTORY` is used.
    Default: None.
user_inputs_mvs_directory : str or None
    Path to MVS specific input directory. If None,
    `constants.DEFAULT_USER_INPUTS_MVS_DIRECTORY` is used.
    Default: None.
```

2021-05-11 14:51 UTC, SabineHaas commented on pvcompare/demand.py
Could you add a line like that to `calculate_heat_demand()`, as well, please?

2021-05-11 14:51 UTC, SabineHaas commented on pvcompare/demand.py
> +    see p.127 in `HOTMAPS<https://www.hotmaps-project.eu/wp-content/uploads/2018/03/D2.3-Hotmaps_for-upload_revised-final_.pdf>`_.
Please add a section "References" below the "Returns" section, where you place the references. Then here you can add the link to the references via `[1]_`.

2021-05-18 14:44 UTC, Piranias commented on pvcompare/demand.py
>          Year for which power demand time series is calculated, needs to be between 2011 - 2015.
the years are 2008 and 2018

2021-05-18 14:46 UTC, Piranias commented on pvcompare/demand.py
>          Year for which power demand time series is calculated. # todo needs to be between 2011 - 2015 like above?
like above

2021-05-18 14:46 UTC, Piranias commented on pvcompare/demand.py
> +# TODO:(nice to have): add function that writes name of demand.csv into energyConsumption.csv'
this todo is deprecated and can be deleted

2021-05-18 14:49 UTC, Piranias commented on pvcompare/demand.py
> +        Year for which power demand time series is calculated TODO: needs to be between 2011 - 2015 like above?
it should say "between 208-2018" (without the todo)

2021-05-20 18:22 UTC, SabineHaas requested changes
@Stefanie08 I will review this PR module wise, I have started with `area_potential` and will go on tomorrow or next week with the rest :)

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
>      facades for a given population.
```suggestion
    facade  depending on `surface_type`.
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
>      Calculates the area potential.
```suggestion
    Calculates the area potential for PV installations.
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
>      Calculates the area potential of the rooftop, south and east/west
```suggestion
    Calculates the area potential of the roof top, south, east or west
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
> +        Area potential of the rooftop.
```suggestion
        Area potential of the roof top, south, east or west facade depending on `surface_type`.
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
>          Directory of the user inputs. If None,
```suggestion
        Path to user input directory. If None,
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
>          `constants.DEFAULT_USER_INPUTS_PVCOMPARE_DIRECTORY` is used as user_inputs_pvcompare_directory.
```suggestion
        `constants.DEFAULT_USER_INPUTS_PVCOMPARE_DIRECTORY` is used.
```

2021-05-20 18:22 UTC, SabineHaas commented on pvcompare/area_potential.py
> +    .. [1] Business Location Center: "Solarpotentialanalyse Berlin – Datendokumentation". Report, 2011
```suggestion
    .. [1] Business Location Center: "Solarpotentialanalyse Berlin – Datendokumentation". Report, 2011, https://energieatlas.berlin.de/Energieatlas_Be/Docs/Datendokumentation-Solarkataster_BLN.pdf
```

2021-05-21 13:35 UTC, SabineHaas requested changes
Thank you again @Stefanie08 ! I will go on with `main.py` next week :)

meanwhile my comments:
- [ ] the linting test of black still fails; maybe you have another version of black, you need black==19.10b0
- [ ] I think there are some modules where the inputs directory parameters have to be adapted still:
```
static_inputs_directory: str or None
    Directory of the pvcompare static inputs. If None,
    `constants.DEFAULT_STATIC_INPUTS_DIRECTORY` is used.
    Default: None.
user_inputs_pvcompare_directory: str or None
    Path to user input directory. If None,
    `constants.DEFAULT_USER_INPUTS_PVCOMPARE_DIRECTORY` is used.
    Default: None.
user_inputs_mvs_directory : str or None
    Path to MVS specific input directory. If None,
    `constants.DEFAULT_USER_INPUTS_MVS_DIRECTORY` is used.
    Default: None.
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +    For these calculations the oemof.thermal :py:func:`~.calc_cops` functionality is
```suggestion
    For these calculations the ``calc_cops()` <functionality>`_ functionality of `oemof.thermal <https://oemof-thermal.readthedocs.io/en/stable/>`_  is
```
You couldn't know, this time the function is outside pvcompare.

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +    None
This was actually right, please revert. 
Maybe this was confusing as there is a function within the function ;)

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +        `Temperature` can be passed in the following way:
```suggestion
        `temperature` can be passed in the following way:
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +        efficiency_series : :pandas:`pandas.Series<series>`
```suggestion
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +            COP or EER time series of heat pump or chiller depending on `mode`.
```suggestion
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
> +    Depending on the case, updates `energyConversion.csv` and saves calculated cops to
```suggestion
        Depending on the case, updates `energyConversion.csv` and saves calculated cops to
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/heat_pump_and_chiller.py
>      'data/mvs_inputs/time_series'.
```suggestion
        'data/mvs_inputs/time_series'.
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +of the pv feed-in time series and the nominal values /installation capacities based on the building
```suggestion
of the pv generation time series and the nominal values /installation capacities based on the building
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +parameters. By adding the heat pump to the energy system, COPs will be calculated as well.
```suggestion
parameters. By adding a heat pump to the energy system, COPs will be calculated as well.
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +        Latitude of country location in 'country'. Default: None.
```suggestion
        Latitude of country location in `country`. Default: None.
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +        Longitude of country location in 'country'. Default: None.
```suggestion
        Longitude of country location in `country`. Default: None.
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +    collections_mvs_inputs_directory: TODO: Parameter missing in pvcompare as well
@Piranias not sure why this is needed here, could you write a description here please?

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
>          mvs input csv'S automatically: electricity price, feed-in tariff,
```suggestion
        MVS input csvs automatically: electricity price, feed-in tariff,
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +        If True, the pv components in energyProduction.csv are
```suggestion
        If True, the pv components in 'energyProduction.csv' are
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
> +    weather: :pandas:`pandas.DataFrame<frame>` TODO: Please check if correct file
```suggestion
    None
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
>      Saves calculated time series to `timeseries` folder in `user_inputs_mvs_directory and
```suggestion
        Saves calculated time series to `timeseries` folder in `user_inputs_mvs_directory` and
```

2021-05-21 13:35 UTC, SabineHaas commented on pvcompare/main.py
>      updates csv files in `csv_elements` folder.
```suggestion
        updates csv files in `csv_elements` folder.
```

2021-05-25 10:37 UTC, SabineHaas requested changes
@Stefanie08 I think I only miss `plots.py`. Will review now.

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/main.py
>      Stores simulation results in `mvs_output_directory`.
```suggestion
        Stores simulation results in directory according to `outputs_directory` and `scenario_name` in 'outputs_directory/scenario_name/mvs_outputs'.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/main.py
Please adapt description of `mvs_output_directory` in this function to: 
```
        This parameter should be set to None. It is filled in automatically
        according to `outputs_directory` and `scenario_name`:
        'outputs_directory/scenario_name/mvs_outputs'.
        Default: None.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Latitude of technology
```suggestion
        Latitude of location
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Longitude of technology
```suggestion
        Longitude of location
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        if None: ./data/mvs_inputs/ TODO: should this information be used?
```suggestion
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        "Korte" or "Chen" TODO: Is there more information for terms Korte and Chen?
For more information please add this link to RTD: https://pvcompare.readthedocs.io/en/latest/model_assumptions.html#input-data

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    Maximum installed capacity (nominal value): :pandas:`pandas.DataFrame<frame>`
```suggestion
    Maximum installed capacity (nominal value): float
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    Area potential: :pandas:`pandas.DataFrame<frame>`
```suggestion
    Area potential: float
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      -------
Could you indent everything after "None" please? I hope this will move the list entries on level to the right, see https://pvcompare--309.org.readthedocs.build/en/309/temp/pvcompare.pv_feedin.create_pv_components.html#pvcompare.pv_feedin.create_pv_components

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      e.G. about 27° to 34° from ground in Germany.
```suggestion
    e.g. about 27° to 34° from ground in Germany.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    The `pvlib <https://pvlib-python.readthedocs.io/en/stable/index.html>`_. uses TODO: Correct Link?
```suggestion
    The `pvlib <https://pvlib-python.readthedocs.io/en/stable/index.html>`_. uses
```
:+1:

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    rounded angle: int
```suggestion
    int
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    rounded angle: int
Because there's no parameter named `rounded angle` but a value is directly returned by `round(lat - 15)`

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Rounded angle for surface tilt
```suggestion
        Angle for optimal surface tilt of `lat`, rounded to zero decimal places.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    TODO: Reference to the pvlibPVSystems?
@Piranias

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      If `normalization`is not None the time
```suggestion
    If `normalization` is True the time series is normalized.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Latitude of the technology.
```suggestion
        Latitude of the location.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Longitude of the technology.
```suggestion
        Longitude of the location.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
```suggestion
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    Cpv time series: :pandas:`pandas.Series<series>`
```suggestion
    :pandas:`pandas.Series<series>`
        Feed-in time series of silicon module.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    series is normalized according to the normalization method.
```suggestion
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
@Piranias  delete next two lines? Here SI time series are calculated. Or is this information for the flat plate module of hybrid CPV?

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      for the INSOLIGHT CPV module. If `normalization`is not None the time
```suggestion
    for the INSOLIGHT CPV module. If `normalization` is True the time
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    series is normalized according to the normalization method.
```suggestion
    series is normalized.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        `wind_speed` in m/s, `dni`, `dhi` and `ghi` in W/m².
Please exchange the sign ` with ' here. I know it's not everywhere consistent but I try to use `` for parameters only.

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    apply_cpvlib_StaticHybridSystem.create_cpv_time_series: :pandas:`pandas.Series<series>`
```suggestion
    :pandas:`pandas.Series<series>`
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>          Power output of CPV module in W.
```suggestion
        Power output time series of CPV module in W.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      Creates power time series of a CPV module.
@Piranias hybrid module?

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      Creates power time series of a Perovskite-Silicone module.
```suggestion
    Creates power time series of a perovskite-silicone (PSI) module.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    `weather`. If `normalization`is not None the time
```suggestion
    `weather`. If `normalization` is True the time series is normalized.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      series is normalized according to the normalization method.
```suggestion
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Power output of PSI module in W (if parameter `normalized` is False) or TODO: check unit.
@Piranias please check unit

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +    installed capacity of PV in oemof.
```suggestion
    maximum installed capacity of PV in the energy system optimization.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
>      This function returns the peak value for the given technology.
```suggestion
    This function returns the peak value for the given `technology`.
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        If technology == si, set parameter to None
```suggestion
        If `technology` is 'si', set parameter to None
```

2021-05-25 10:37 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Peak value used for normalization.
```suggestion
        Peak value of the `technology`.
```

2021-05-25 10:52 UTC, SabineHaas requested changes
Thank you @Stefanie08 :) 

As I am not sure whether @Piranias  will be able to work on the further todos in this PR soon, please remove the open TODOs of the `plots.py` module in a single commit "Remove todos". This ways they are still documented in this PR.

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +        Latitude of country location in 'country'.
```suggestion
        Latitude of country location in `country`.
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +        Longitude of country location in 'country'.
```suggestion
        Longitude of country location in `country`.
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Plots list of KPI's of a 'mvs_output/scalars_**.xlsx' file. TODO: What does the abbreviation KPI mean?
```suggestion
    Plots list of key performance indicators (KPIs) of a 'mvs_output/scalars_**.xlsx' file.
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:52 UTC, SabineHaas commented on pvcompare/plots.py
> +    Figure: png
```suggestion
```

2021-05-25 10:56 UTC, SabineHaas commented on pvcompare/main.py
@Piranias in the parameter description of `apply_mvs()` it says that the `scenario_name` has to follow a certain scheme - this is only the case, when the user wants to plot the scenarios afterwards, right?

2021-05-25 11:27 UTC, Piranias commented on pvcompare/main.py
actually I think it does not need to follow this rule, also not for the plots! So this is deprecated.

2021-05-27 14:49 UTC, Stefanie08 commented on pvcompare/main.py
@SabineHaas @Piranias should I delete the line in all functions?

2021-05-27 15:07 UTC, SabineHaas commented on pvcompare/main.py
Yes, I think so.

2021-05-27 16:08 UTC, SabineHaas commented on pvcompare/pv_feedin.py
> +        Power output of PSI module in W (if parameter `normalized` is False) or
@Piranias is the unit correct? there was a todo

2021-05-27 16:09 UTC, SabineHaas commented on pvcompare/demand.py
> +        Year can be chosen between 2008 and 2018.
@Piranias correct? 2008 - 2018 for heat demand

2021-05-28 06:40 UTC, Piranias commented on pvcompare/pv_feedin.py
> +        Power output of PSI module in W (if parameter `normalized` is False) or
yes, its correct, the todo can be removed

2021-05-28 06:41 UTC, Piranias commented on pvcompare/demand.py
> +        Year can be chosen between 2008 and 2018.
yes, this is correct

2021-05-28 06:42 UTC, Piranias commented on pvcompare/main.py
yes, the line where it says that a scheme is required, can go!

2021-05-28 06:51 UTC, Piranias commented on pvcompare/main.py
> +    collections_mvs_inputs_directory: TODO: Parameter missing in pvcompare as well
@SabineHaas , are you asking about the TODO?  I don't know what parameter should be missing. If all parameters are in the docstring, just delete the todo

2021-05-28 06:51 UTC, Piranias commented on pvcompare/pv_feedin.py
ups, ok. So it should say "si" instead of "cpv" and the module is the “Aleo_Solar_S59y280” module, not the "Canadian ..."

2021-05-28 06:51 UTC, Piranias commented on pvcompare/pv_feedin.py
the rest can stay

2021-05-28 06:51 UTC, Piranias commented on pvcompare/pv_feedin.py
> +        Power output of PSI module in W (if parameter `normalized` is False) or TODO: check unit.
W is correct

2021-05-28 06:51 UTC, Piranias commented on pvcompare/pv_feedin.py
>      Creates power time series of a CPV module.
yes, hybrid would be more correct!

2021-05-28 08:53 UTC, Stefanie08 commented on pvcompare/main.py
Okay!

2021-05-28 09:21 UTC, SabineHaas commented on pvcompare/main.py
> +        This parameter should be set to None. It is filled in automatically
@Piranias is this parameter actually needed? If not, i would NOT change this now in this PR.

2021-05-28 10:18 UTC, SabineHaas approved these changes
Thank you @Stefanie08 

I only have two comments/suggestions. 
So, I already approve this PR.

@Piranias do you want to have a quick view as well before merging?

2021-05-28 10:18 UTC, SabineHaas commented on pvcompare/check_inputs.py
> +    year: int
Please add a description to each of the return values

2021-05-28 10:18 UTC, SabineHaas commented on pvcompare/check_inputs.py
> +    pvcompare_parameter: str
I think there are many possible types apart from string, but not sure. @Piranias could you add the types please?

2021-05-28 10:27 UTC, SabineHaas commented on pvcompare/check_inputs.py
> +    nominal_storage_capacity : float
@MaGering should the type here be `numeric` or `float` or something else?

2021-05-28 10:28 UTC, SabineHaas commented on pvcompare/check_inputs.py
> +    loss_rate : float (sequence or scalar)
@MaGering should the type here be `numeric` or `float` or something else?

2021-05-28 10:33 UTC, Piranias commented on pvcompare/check_inputs.py
> +    pvcompare_parameter: str
str, float, int

2021-05-28 10:33 UTC, Piranias commented on pvcompare/cpv/apply_cpvlib_StaticHybridSystem.py
> +    Calculates maximum power output and efficiency for the CPV cells and flat plate module.
```suggestion
    Calculates maximum power output and efficiency for the CPV and flat plate module.
```

2021-05-28 10:47 UTC, Piranias approved these changes

2021-05-28 12:33 UTC, MaGering commented on pvcompare/check_inputs.py
> +    nominal_storage_capacity : float
It can be either float or int. So if it is ok to write "numeric", I'd preferred that.

2021-05-28 13:14 UTC, merged